// Generated by CIRCT firtool-1.144.0
module CuperSpmvChisel8(
  input          ap_clk,
                 ap_rst_n,
  output         interrupt,
  input          s_axi_control_AWVALID,
  output         s_axi_control_AWREADY,
  input  [11:0]  s_axi_control_AWADDR,
  input          s_axi_control_WVALID,
  output         s_axi_control_WREADY,
  input  [31:0]  s_axi_control_WDATA,
  input  [3:0]   s_axi_control_WSTRB,
  input          s_axi_control_ARVALID,
  output         s_axi_control_ARREADY,
  input  [11:0]  s_axi_control_ARADDR,
  output         s_axi_control_RVALID,
  input          s_axi_control_RREADY,
  output [31:0]  s_axi_control_RDATA,
  output [1:0]   s_axi_control_RRESP,
  output         s_axi_control_BVALID,
  input          s_axi_control_BREADY,
  output [1:0]   s_axi_control_BRESP,
  output [63:0]  m_axi_SpElement_list_ptr_AWADDR,
  output [1:0]   m_axi_SpElement_list_ptr_AWBURST,
  output [3:0]   m_axi_SpElement_list_ptr_AWCACHE,
  output         m_axi_SpElement_list_ptr_AWID,
  output [7:0]   m_axi_SpElement_list_ptr_AWLEN,
  output         m_axi_SpElement_list_ptr_AWLOCK,
  output [2:0]   m_axi_SpElement_list_ptr_AWPROT,
  output [3:0]   m_axi_SpElement_list_ptr_AWQOS,
  input          m_axi_SpElement_list_ptr_AWREADY,
  output [2:0]   m_axi_SpElement_list_ptr_AWSIZE,
  output         m_axi_SpElement_list_ptr_AWVALID,
  input          m_axi_SpElement_list_ptr_BID,
  output         m_axi_SpElement_list_ptr_BREADY,
  input  [1:0]   m_axi_SpElement_list_ptr_BRESP,
  input          m_axi_SpElement_list_ptr_BVALID,
  output [63:0]  m_axi_SpElement_list_ptr_ARADDR,
  output [1:0]   m_axi_SpElement_list_ptr_ARBURST,
  output [3:0]   m_axi_SpElement_list_ptr_ARCACHE,
  output         m_axi_SpElement_list_ptr_ARID,
  output [7:0]   m_axi_SpElement_list_ptr_ARLEN,
  output         m_axi_SpElement_list_ptr_ARLOCK,
  output [2:0]   m_axi_SpElement_list_ptr_ARPROT,
  output [3:0]   m_axi_SpElement_list_ptr_ARQOS,
  input          m_axi_SpElement_list_ptr_ARREADY,
  output [2:0]   m_axi_SpElement_list_ptr_ARSIZE,
  output         m_axi_SpElement_list_ptr_ARVALID,
  input  [31:0]  m_axi_SpElement_list_ptr_RDATA,
  input          m_axi_SpElement_list_ptr_RID,
                 m_axi_SpElement_list_ptr_RLAST,
  output         m_axi_SpElement_list_ptr_RREADY,
  input  [1:0]   m_axi_SpElement_list_ptr_RRESP,
  input          m_axi_SpElement_list_ptr_RVALID,
  output [31:0]  m_axi_SpElement_list_ptr_WDATA,
  output         m_axi_SpElement_list_ptr_WLAST,
  input          m_axi_SpElement_list_ptr_WREADY,
  output [3:0]   m_axi_SpElement_list_ptr_WSTRB,
  output         m_axi_SpElement_list_ptr_WVALID,
  output [63:0]  m_axi_Matrix_data_0_AWADDR,
  output [1:0]   m_axi_Matrix_data_0_AWBURST,
  output [3:0]   m_axi_Matrix_data_0_AWCACHE,
  output         m_axi_Matrix_data_0_AWID,
  output [7:0]   m_axi_Matrix_data_0_AWLEN,
  output         m_axi_Matrix_data_0_AWLOCK,
  output [2:0]   m_axi_Matrix_data_0_AWPROT,
  output [3:0]   m_axi_Matrix_data_0_AWQOS,
  input          m_axi_Matrix_data_0_AWREADY,
  output [2:0]   m_axi_Matrix_data_0_AWSIZE,
  output         m_axi_Matrix_data_0_AWVALID,
  input          m_axi_Matrix_data_0_BID,
  output         m_axi_Matrix_data_0_BREADY,
  input  [1:0]   m_axi_Matrix_data_0_BRESP,
  input          m_axi_Matrix_data_0_BVALID,
  output [63:0]  m_axi_Matrix_data_0_ARADDR,
  output [1:0]   m_axi_Matrix_data_0_ARBURST,
  output [3:0]   m_axi_Matrix_data_0_ARCACHE,
  output         m_axi_Matrix_data_0_ARID,
  output [7:0]   m_axi_Matrix_data_0_ARLEN,
  output         m_axi_Matrix_data_0_ARLOCK,
  output [2:0]   m_axi_Matrix_data_0_ARPROT,
  output [3:0]   m_axi_Matrix_data_0_ARQOS,
  input          m_axi_Matrix_data_0_ARREADY,
  output [2:0]   m_axi_Matrix_data_0_ARSIZE,
  output         m_axi_Matrix_data_0_ARVALID,
  input  [511:0] m_axi_Matrix_data_0_RDATA,
  input          m_axi_Matrix_data_0_RID,
                 m_axi_Matrix_data_0_RLAST,
  output         m_axi_Matrix_data_0_RREADY,
  input  [1:0]   m_axi_Matrix_data_0_RRESP,
  input          m_axi_Matrix_data_0_RVALID,
  output [511:0] m_axi_Matrix_data_0_WDATA,
  output         m_axi_Matrix_data_0_WLAST,
  input          m_axi_Matrix_data_0_WREADY,
  output [63:0]  m_axi_Matrix_data_0_WSTRB,
  output         m_axi_Matrix_data_0_WVALID,
  output [63:0]  m_axi_Matrix_data_1_AWADDR,
  output [1:0]   m_axi_Matrix_data_1_AWBURST,
  output [3:0]   m_axi_Matrix_data_1_AWCACHE,
  output         m_axi_Matrix_data_1_AWID,
  output [7:0]   m_axi_Matrix_data_1_AWLEN,
  output         m_axi_Matrix_data_1_AWLOCK,
  output [2:0]   m_axi_Matrix_data_1_AWPROT,
  output [3:0]   m_axi_Matrix_data_1_AWQOS,
  input          m_axi_Matrix_data_1_AWREADY,
  output [2:0]   m_axi_Matrix_data_1_AWSIZE,
  output         m_axi_Matrix_data_1_AWVALID,
  input          m_axi_Matrix_data_1_BID,
  output         m_axi_Matrix_data_1_BREADY,
  input  [1:0]   m_axi_Matrix_data_1_BRESP,
  input          m_axi_Matrix_data_1_BVALID,
  output [63:0]  m_axi_Matrix_data_1_ARADDR,
  output [1:0]   m_axi_Matrix_data_1_ARBURST,
  output [3:0]   m_axi_Matrix_data_1_ARCACHE,
  output         m_axi_Matrix_data_1_ARID,
  output [7:0]   m_axi_Matrix_data_1_ARLEN,
  output         m_axi_Matrix_data_1_ARLOCK,
  output [2:0]   m_axi_Matrix_data_1_ARPROT,
  output [3:0]   m_axi_Matrix_data_1_ARQOS,
  input          m_axi_Matrix_data_1_ARREADY,
  output [2:0]   m_axi_Matrix_data_1_ARSIZE,
  output         m_axi_Matrix_data_1_ARVALID,
  input  [511:0] m_axi_Matrix_data_1_RDATA,
  input          m_axi_Matrix_data_1_RID,
                 m_axi_Matrix_data_1_RLAST,
  output         m_axi_Matrix_data_1_RREADY,
  input  [1:0]   m_axi_Matrix_data_1_RRESP,
  input          m_axi_Matrix_data_1_RVALID,
  output [511:0] m_axi_Matrix_data_1_WDATA,
  output         m_axi_Matrix_data_1_WLAST,
  input          m_axi_Matrix_data_1_WREADY,
  output [63:0]  m_axi_Matrix_data_1_WSTRB,
  output         m_axi_Matrix_data_1_WVALID,
  output [63:0]  m_axi_Matrix_data_2_AWADDR,
  output [1:0]   m_axi_Matrix_data_2_AWBURST,
  output [3:0]   m_axi_Matrix_data_2_AWCACHE,
  output         m_axi_Matrix_data_2_AWID,
  output [7:0]   m_axi_Matrix_data_2_AWLEN,
  output         m_axi_Matrix_data_2_AWLOCK,
  output [2:0]   m_axi_Matrix_data_2_AWPROT,
  output [3:0]   m_axi_Matrix_data_2_AWQOS,
  input          m_axi_Matrix_data_2_AWREADY,
  output [2:0]   m_axi_Matrix_data_2_AWSIZE,
  output         m_axi_Matrix_data_2_AWVALID,
  input          m_axi_Matrix_data_2_BID,
  output         m_axi_Matrix_data_2_BREADY,
  input  [1:0]   m_axi_Matrix_data_2_BRESP,
  input          m_axi_Matrix_data_2_BVALID,
  output [63:0]  m_axi_Matrix_data_2_ARADDR,
  output [1:0]   m_axi_Matrix_data_2_ARBURST,
  output [3:0]   m_axi_Matrix_data_2_ARCACHE,
  output         m_axi_Matrix_data_2_ARID,
  output [7:0]   m_axi_Matrix_data_2_ARLEN,
  output         m_axi_Matrix_data_2_ARLOCK,
  output [2:0]   m_axi_Matrix_data_2_ARPROT,
  output [3:0]   m_axi_Matrix_data_2_ARQOS,
  input          m_axi_Matrix_data_2_ARREADY,
  output [2:0]   m_axi_Matrix_data_2_ARSIZE,
  output         m_axi_Matrix_data_2_ARVALID,
  input  [511:0] m_axi_Matrix_data_2_RDATA,
  input          m_axi_Matrix_data_2_RID,
                 m_axi_Matrix_data_2_RLAST,
  output         m_axi_Matrix_data_2_RREADY,
  input  [1:0]   m_axi_Matrix_data_2_RRESP,
  input          m_axi_Matrix_data_2_RVALID,
  output [511:0] m_axi_Matrix_data_2_WDATA,
  output         m_axi_Matrix_data_2_WLAST,
  input          m_axi_Matrix_data_2_WREADY,
  output [63:0]  m_axi_Matrix_data_2_WSTRB,
  output         m_axi_Matrix_data_2_WVALID,
  output [63:0]  m_axi_Matrix_data_3_AWADDR,
  output [1:0]   m_axi_Matrix_data_3_AWBURST,
  output [3:0]   m_axi_Matrix_data_3_AWCACHE,
  output         m_axi_Matrix_data_3_AWID,
  output [7:0]   m_axi_Matrix_data_3_AWLEN,
  output         m_axi_Matrix_data_3_AWLOCK,
  output [2:0]   m_axi_Matrix_data_3_AWPROT,
  output [3:0]   m_axi_Matrix_data_3_AWQOS,
  input          m_axi_Matrix_data_3_AWREADY,
  output [2:0]   m_axi_Matrix_data_3_AWSIZE,
  output         m_axi_Matrix_data_3_AWVALID,
  input          m_axi_Matrix_data_3_BID,
  output         m_axi_Matrix_data_3_BREADY,
  input  [1:0]   m_axi_Matrix_data_3_BRESP,
  input          m_axi_Matrix_data_3_BVALID,
  output [63:0]  m_axi_Matrix_data_3_ARADDR,
  output [1:0]   m_axi_Matrix_data_3_ARBURST,
  output [3:0]   m_axi_Matrix_data_3_ARCACHE,
  output         m_axi_Matrix_data_3_ARID,
  output [7:0]   m_axi_Matrix_data_3_ARLEN,
  output         m_axi_Matrix_data_3_ARLOCK,
  output [2:0]   m_axi_Matrix_data_3_ARPROT,
  output [3:0]   m_axi_Matrix_data_3_ARQOS,
  input          m_axi_Matrix_data_3_ARREADY,
  output [2:0]   m_axi_Matrix_data_3_ARSIZE,
  output         m_axi_Matrix_data_3_ARVALID,
  input  [511:0] m_axi_Matrix_data_3_RDATA,
  input          m_axi_Matrix_data_3_RID,
                 m_axi_Matrix_data_3_RLAST,
  output         m_axi_Matrix_data_3_RREADY,
  input  [1:0]   m_axi_Matrix_data_3_RRESP,
  input          m_axi_Matrix_data_3_RVALID,
  output [511:0] m_axi_Matrix_data_3_WDATA,
  output         m_axi_Matrix_data_3_WLAST,
  input          m_axi_Matrix_data_3_WREADY,
  output [63:0]  m_axi_Matrix_data_3_WSTRB,
  output         m_axi_Matrix_data_3_WVALID,
  output [63:0]  m_axi_Matrix_data_4_AWADDR,
  output [1:0]   m_axi_Matrix_data_4_AWBURST,
  output [3:0]   m_axi_Matrix_data_4_AWCACHE,
  output         m_axi_Matrix_data_4_AWID,
  output [7:0]   m_axi_Matrix_data_4_AWLEN,
  output         m_axi_Matrix_data_4_AWLOCK,
  output [2:0]   m_axi_Matrix_data_4_AWPROT,
  output [3:0]   m_axi_Matrix_data_4_AWQOS,
  input          m_axi_Matrix_data_4_AWREADY,
  output [2:0]   m_axi_Matrix_data_4_AWSIZE,
  output         m_axi_Matrix_data_4_AWVALID,
  input          m_axi_Matrix_data_4_BID,
  output         m_axi_Matrix_data_4_BREADY,
  input  [1:0]   m_axi_Matrix_data_4_BRESP,
  input          m_axi_Matrix_data_4_BVALID,
  output [63:0]  m_axi_Matrix_data_4_ARADDR,
  output [1:0]   m_axi_Matrix_data_4_ARBURST,
  output [3:0]   m_axi_Matrix_data_4_ARCACHE,
  output         m_axi_Matrix_data_4_ARID,
  output [7:0]   m_axi_Matrix_data_4_ARLEN,
  output         m_axi_Matrix_data_4_ARLOCK,
  output [2:0]   m_axi_Matrix_data_4_ARPROT,
  output [3:0]   m_axi_Matrix_data_4_ARQOS,
  input          m_axi_Matrix_data_4_ARREADY,
  output [2:0]   m_axi_Matrix_data_4_ARSIZE,
  output         m_axi_Matrix_data_4_ARVALID,
  input  [511:0] m_axi_Matrix_data_4_RDATA,
  input          m_axi_Matrix_data_4_RID,
                 m_axi_Matrix_data_4_RLAST,
  output         m_axi_Matrix_data_4_RREADY,
  input  [1:0]   m_axi_Matrix_data_4_RRESP,
  input          m_axi_Matrix_data_4_RVALID,
  output [511:0] m_axi_Matrix_data_4_WDATA,
  output         m_axi_Matrix_data_4_WLAST,
  input          m_axi_Matrix_data_4_WREADY,
  output [63:0]  m_axi_Matrix_data_4_WSTRB,
  output         m_axi_Matrix_data_4_WVALID,
  output [63:0]  m_axi_Matrix_data_5_AWADDR,
  output [1:0]   m_axi_Matrix_data_5_AWBURST,
  output [3:0]   m_axi_Matrix_data_5_AWCACHE,
  output         m_axi_Matrix_data_5_AWID,
  output [7:0]   m_axi_Matrix_data_5_AWLEN,
  output         m_axi_Matrix_data_5_AWLOCK,
  output [2:0]   m_axi_Matrix_data_5_AWPROT,
  output [3:0]   m_axi_Matrix_data_5_AWQOS,
  input          m_axi_Matrix_data_5_AWREADY,
  output [2:0]   m_axi_Matrix_data_5_AWSIZE,
  output         m_axi_Matrix_data_5_AWVALID,
  input          m_axi_Matrix_data_5_BID,
  output         m_axi_Matrix_data_5_BREADY,
  input  [1:0]   m_axi_Matrix_data_5_BRESP,
  input          m_axi_Matrix_data_5_BVALID,
  output [63:0]  m_axi_Matrix_data_5_ARADDR,
  output [1:0]   m_axi_Matrix_data_5_ARBURST,
  output [3:0]   m_axi_Matrix_data_5_ARCACHE,
  output         m_axi_Matrix_data_5_ARID,
  output [7:0]   m_axi_Matrix_data_5_ARLEN,
  output         m_axi_Matrix_data_5_ARLOCK,
  output [2:0]   m_axi_Matrix_data_5_ARPROT,
  output [3:0]   m_axi_Matrix_data_5_ARQOS,
  input          m_axi_Matrix_data_5_ARREADY,
  output [2:0]   m_axi_Matrix_data_5_ARSIZE,
  output         m_axi_Matrix_data_5_ARVALID,
  input  [511:0] m_axi_Matrix_data_5_RDATA,
  input          m_axi_Matrix_data_5_RID,
                 m_axi_Matrix_data_5_RLAST,
  output         m_axi_Matrix_data_5_RREADY,
  input  [1:0]   m_axi_Matrix_data_5_RRESP,
  input          m_axi_Matrix_data_5_RVALID,
  output [511:0] m_axi_Matrix_data_5_WDATA,
  output         m_axi_Matrix_data_5_WLAST,
  input          m_axi_Matrix_data_5_WREADY,
  output [63:0]  m_axi_Matrix_data_5_WSTRB,
  output         m_axi_Matrix_data_5_WVALID,
  output [63:0]  m_axi_Matrix_data_6_AWADDR,
  output [1:0]   m_axi_Matrix_data_6_AWBURST,
  output [3:0]   m_axi_Matrix_data_6_AWCACHE,
  output         m_axi_Matrix_data_6_AWID,
  output [7:0]   m_axi_Matrix_data_6_AWLEN,
  output         m_axi_Matrix_data_6_AWLOCK,
  output [2:0]   m_axi_Matrix_data_6_AWPROT,
  output [3:0]   m_axi_Matrix_data_6_AWQOS,
  input          m_axi_Matrix_data_6_AWREADY,
  output [2:0]   m_axi_Matrix_data_6_AWSIZE,
  output         m_axi_Matrix_data_6_AWVALID,
  input          m_axi_Matrix_data_6_BID,
  output         m_axi_Matrix_data_6_BREADY,
  input  [1:0]   m_axi_Matrix_data_6_BRESP,
  input          m_axi_Matrix_data_6_BVALID,
  output [63:0]  m_axi_Matrix_data_6_ARADDR,
  output [1:0]   m_axi_Matrix_data_6_ARBURST,
  output [3:0]   m_axi_Matrix_data_6_ARCACHE,
  output         m_axi_Matrix_data_6_ARID,
  output [7:0]   m_axi_Matrix_data_6_ARLEN,
  output         m_axi_Matrix_data_6_ARLOCK,
  output [2:0]   m_axi_Matrix_data_6_ARPROT,
  output [3:0]   m_axi_Matrix_data_6_ARQOS,
  input          m_axi_Matrix_data_6_ARREADY,
  output [2:0]   m_axi_Matrix_data_6_ARSIZE,
  output         m_axi_Matrix_data_6_ARVALID,
  input  [511:0] m_axi_Matrix_data_6_RDATA,
  input          m_axi_Matrix_data_6_RID,
                 m_axi_Matrix_data_6_RLAST,
  output         m_axi_Matrix_data_6_RREADY,
  input  [1:0]   m_axi_Matrix_data_6_RRESP,
  input          m_axi_Matrix_data_6_RVALID,
  output [511:0] m_axi_Matrix_data_6_WDATA,
  output         m_axi_Matrix_data_6_WLAST,
  input          m_axi_Matrix_data_6_WREADY,
  output [63:0]  m_axi_Matrix_data_6_WSTRB,
  output         m_axi_Matrix_data_6_WVALID,
  output [63:0]  m_axi_Matrix_data_7_AWADDR,
  output [1:0]   m_axi_Matrix_data_7_AWBURST,
  output [3:0]   m_axi_Matrix_data_7_AWCACHE,
  output         m_axi_Matrix_data_7_AWID,
  output [7:0]   m_axi_Matrix_data_7_AWLEN,
  output         m_axi_Matrix_data_7_AWLOCK,
  output [2:0]   m_axi_Matrix_data_7_AWPROT,
  output [3:0]   m_axi_Matrix_data_7_AWQOS,
  input          m_axi_Matrix_data_7_AWREADY,
  output [2:0]   m_axi_Matrix_data_7_AWSIZE,
  output         m_axi_Matrix_data_7_AWVALID,
  input          m_axi_Matrix_data_7_BID,
  output         m_axi_Matrix_data_7_BREADY,
  input  [1:0]   m_axi_Matrix_data_7_BRESP,
  input          m_axi_Matrix_data_7_BVALID,
  output [63:0]  m_axi_Matrix_data_7_ARADDR,
  output [1:0]   m_axi_Matrix_data_7_ARBURST,
  output [3:0]   m_axi_Matrix_data_7_ARCACHE,
  output         m_axi_Matrix_data_7_ARID,
  output [7:0]   m_axi_Matrix_data_7_ARLEN,
  output         m_axi_Matrix_data_7_ARLOCK,
  output [2:0]   m_axi_Matrix_data_7_ARPROT,
  output [3:0]   m_axi_Matrix_data_7_ARQOS,
  input          m_axi_Matrix_data_7_ARREADY,
  output [2:0]   m_axi_Matrix_data_7_ARSIZE,
  output         m_axi_Matrix_data_7_ARVALID,
  input  [511:0] m_axi_Matrix_data_7_RDATA,
  input          m_axi_Matrix_data_7_RID,
                 m_axi_Matrix_data_7_RLAST,
  output         m_axi_Matrix_data_7_RREADY,
  input  [1:0]   m_axi_Matrix_data_7_RRESP,
  input          m_axi_Matrix_data_7_RVALID,
  output [511:0] m_axi_Matrix_data_7_WDATA,
  output         m_axi_Matrix_data_7_WLAST,
  input          m_axi_Matrix_data_7_WREADY,
  output [63:0]  m_axi_Matrix_data_7_WSTRB,
  output         m_axi_Matrix_data_7_WVALID,
  output [63:0]  m_axi_X_AWADDR,
  output [1:0]   m_axi_X_AWBURST,
  output [3:0]   m_axi_X_AWCACHE,
  output         m_axi_X_AWID,
  output [7:0]   m_axi_X_AWLEN,
  output         m_axi_X_AWLOCK,
  output [2:0]   m_axi_X_AWPROT,
  output [3:0]   m_axi_X_AWQOS,
  input          m_axi_X_AWREADY,
  output [2:0]   m_axi_X_AWSIZE,
  output         m_axi_X_AWVALID,
  input          m_axi_X_BID,
  output         m_axi_X_BREADY,
  input  [1:0]   m_axi_X_BRESP,
  input          m_axi_X_BVALID,
  output [63:0]  m_axi_X_ARADDR,
  output [1:0]   m_axi_X_ARBURST,
  output [3:0]   m_axi_X_ARCACHE,
  output         m_axi_X_ARID,
  output [7:0]   m_axi_X_ARLEN,
  output         m_axi_X_ARLOCK,
  output [2:0]   m_axi_X_ARPROT,
  output [3:0]   m_axi_X_ARQOS,
  input          m_axi_X_ARREADY,
  output [2:0]   m_axi_X_ARSIZE,
  output         m_axi_X_ARVALID,
  input  [511:0] m_axi_X_RDATA,
  input          m_axi_X_RID,
                 m_axi_X_RLAST,
  output         m_axi_X_RREADY,
  input  [1:0]   m_axi_X_RRESP,
  input          m_axi_X_RVALID,
  output [511:0] m_axi_X_WDATA,
  output         m_axi_X_WLAST,
  input          m_axi_X_WREADY,
  output [63:0]  m_axi_X_WSTRB,
  output         m_axi_X_WVALID,
  output [63:0]  m_axi_Y_out_AWADDR,
  output [1:0]   m_axi_Y_out_AWBURST,
  output [3:0]   m_axi_Y_out_AWCACHE,
  output         m_axi_Y_out_AWID,
  output [7:0]   m_axi_Y_out_AWLEN,
  output         m_axi_Y_out_AWLOCK,
  output [2:0]   m_axi_Y_out_AWPROT,
  output [3:0]   m_axi_Y_out_AWQOS,
  input          m_axi_Y_out_AWREADY,
  output [2:0]   m_axi_Y_out_AWSIZE,
  output         m_axi_Y_out_AWVALID,
  input          m_axi_Y_out_BID,
  output         m_axi_Y_out_BREADY,
  input  [1:0]   m_axi_Y_out_BRESP,
  input          m_axi_Y_out_BVALID,
  output [63:0]  m_axi_Y_out_ARADDR,
  output [1:0]   m_axi_Y_out_ARBURST,
  output [3:0]   m_axi_Y_out_ARCACHE,
  output         m_axi_Y_out_ARID,
  output [7:0]   m_axi_Y_out_ARLEN,
  output         m_axi_Y_out_ARLOCK,
  output [2:0]   m_axi_Y_out_ARPROT,
  output [3:0]   m_axi_Y_out_ARQOS,
  input          m_axi_Y_out_ARREADY,
  output [2:0]   m_axi_Y_out_ARSIZE,
  output         m_axi_Y_out_ARVALID,
  input  [31:0]  m_axi_Y_out_RDATA,
  input          m_axi_Y_out_RID,
                 m_axi_Y_out_RLAST,
  output         m_axi_Y_out_RREADY,
  input  [1:0]   m_axi_Y_out_RRESP,
  input          m_axi_Y_out_RVALID,
  output [31:0]  m_axi_Y_out_WDATA,
  output         m_axi_Y_out_WLAST,
  input          m_axi_Y_out_WREADY,
  output [3:0]   m_axi_Y_out_WSTRB,
  output         m_axi_Y_out_WVALID,
  output [63:0]  m_axi_Status_AWADDR,
  output [1:0]   m_axi_Status_AWBURST,
  output [3:0]   m_axi_Status_AWCACHE,
  output         m_axi_Status_AWID,
  output [7:0]   m_axi_Status_AWLEN,
  output         m_axi_Status_AWLOCK,
  output [2:0]   m_axi_Status_AWPROT,
  output [3:0]   m_axi_Status_AWQOS,
  input          m_axi_Status_AWREADY,
  output [2:0]   m_axi_Status_AWSIZE,
  output         m_axi_Status_AWVALID,
  input          m_axi_Status_BID,
  output         m_axi_Status_BREADY,
  input  [1:0]   m_axi_Status_BRESP,
  input          m_axi_Status_BVALID,
  output [63:0]  m_axi_Status_ARADDR,
  output [1:0]   m_axi_Status_ARBURST,
  output [3:0]   m_axi_Status_ARCACHE,
  output         m_axi_Status_ARID,
  output [7:0]   m_axi_Status_ARLEN,
  output         m_axi_Status_ARLOCK,
  output [2:0]   m_axi_Status_ARPROT,
  output [3:0]   m_axi_Status_ARQOS,
  input          m_axi_Status_ARREADY,
  output [2:0]   m_axi_Status_ARSIZE,
  output         m_axi_Status_ARVALID,
  input  [31:0]  m_axi_Status_RDATA,
  input          m_axi_Status_RID,
                 m_axi_Status_RLAST,
  output         m_axi_Status_RREADY,
  input  [1:0]   m_axi_Status_RRESP,
  input          m_axi_Status_RVALID,
  output [31:0]  m_axi_Status_WDATA,
  output         m_axi_Status_WLAST,
  input          m_axi_Status_WREADY,
  output [3:0]   m_axi_Status_WSTRB,
  output         m_axi_Status_WVALID,
  output [63:0]  m_axi_Metrics_AWADDR,
  output [1:0]   m_axi_Metrics_AWBURST,
  output [3:0]   m_axi_Metrics_AWCACHE,
  output         m_axi_Metrics_AWID,
  output [7:0]   m_axi_Metrics_AWLEN,
  output         m_axi_Metrics_AWLOCK,
  output [2:0]   m_axi_Metrics_AWPROT,
  output [3:0]   m_axi_Metrics_AWQOS,
  input          m_axi_Metrics_AWREADY,
  output [2:0]   m_axi_Metrics_AWSIZE,
  output         m_axi_Metrics_AWVALID,
  input          m_axi_Metrics_BID,
  output         m_axi_Metrics_BREADY,
  input  [1:0]   m_axi_Metrics_BRESP,
  input          m_axi_Metrics_BVALID,
  output [63:0]  m_axi_Metrics_ARADDR,
  output [1:0]   m_axi_Metrics_ARBURST,
  output [3:0]   m_axi_Metrics_ARCACHE,
  output         m_axi_Metrics_ARID,
  output [7:0]   m_axi_Metrics_ARLEN,
  output         m_axi_Metrics_ARLOCK,
  output [2:0]   m_axi_Metrics_ARPROT,
  output [3:0]   m_axi_Metrics_ARQOS,
  input          m_axi_Metrics_ARREADY,
  output [2:0]   m_axi_Metrics_ARSIZE,
  output         m_axi_Metrics_ARVALID,
  input  [63:0]  m_axi_Metrics_RDATA,
  input          m_axi_Metrics_RID,
                 m_axi_Metrics_RLAST,
  output         m_axi_Metrics_RREADY,
  input  [1:0]   m_axi_Metrics_RRESP,
  input          m_axi_Metrics_RVALID,
  output [63:0]  m_axi_Metrics_WDATA,
  output         m_axi_Metrics_WLAST,
  input          m_axi_Metrics_WREADY,
  output [7:0]   m_axi_Metrics_WSTRB,
  output         m_axi_Metrics_WVALID
);

  reg  [63:0]  argPtr_0;
  reg  [63:0]  argPtr_1;
  reg  [63:0]  argPtr_2;
  reg  [63:0]  argPtr_3;
  reg  [63:0]  argPtr_4;
  reg  [63:0]  argPtr_5;
  reg  [63:0]  argPtr_6;
  reg  [63:0]  argPtr_7;
  reg  [63:0]  argPtr_8;
  reg  [63:0]  argPtr_9;
  reg  [63:0]  argPtr_10;
  reg  [63:0]  argPtr_11;
  reg  [63:0]  argPtr_12;
  reg  [31:0]  batchNum;
  reg  [31:0]  matrixLen;
  reg  [31:0]  rowNum;
  reg  [31:0]  columnNum;
  reg  [31:0]  iterationNum;
  reg          startPending;
  reg          autoRestart;
  reg          doneSticky;
  reg          awValid;
  reg  [11:0]  awAddr;
  reg          wValid;
  reg  [31:0]  wData;
  reg  [3:0]   wStrb;
  reg          bValid;
  reg  [3:0]   state;
  reg  [2:0]   matrixIndex;
  reg  [4:0]   statusIndex;
  reg  [4:0]   metricIndex;
  reg  [31:0]  ptr0;
  reg  [511:0] x0;
  reg  [511:0] matrixFirst_0;
  reg  [511:0] matrixFirst_1;
  reg  [511:0] matrixFirst_2;
  reg  [511:0] matrixFirst_3;
  reg  [511:0] matrixFirst_4;
  reg  [511:0] matrixFirst_5;
  reg  [511:0] matrixFirst_6;
  reg  [511:0] matrixFirst_7;
  reg  [63:0]  cycleCounter;
  reg  [1:0]   lastBresp;
  reg  [1:0]   lastRresp;
  reg          rValid;
  reg  [31:0]  rData;
  reg          rIsCtrl;
  wire         _selectedMatrixRResp_T_1 = matrixIndex == 3'h1;
  wire         _selectedMatrixRResp_T_2 = matrixIndex == 3'h2;
  wire         _selectedMatrixRResp_T_3 = matrixIndex == 3'h3;
  wire         _selectedMatrixRResp_T_4 = matrixIndex == 3'h4;
  wire         _selectedMatrixRResp_T_5 = matrixIndex == 3'h5;
  wire         _selectedMatrixRResp_T_6 = matrixIndex == 3'h6;
  wire         selectedMatrixRValid =
    ~(|matrixIndex) & m_axi_Matrix_data_0_RVALID | _selectedMatrixRResp_T_1
    & m_axi_Matrix_data_1_RVALID | _selectedMatrixRResp_T_2 & m_axi_Matrix_data_2_RVALID
    | _selectedMatrixRResp_T_3 & m_axi_Matrix_data_3_RVALID | _selectedMatrixRResp_T_4
    & m_axi_Matrix_data_4_RVALID | _selectedMatrixRResp_T_5 & m_axi_Matrix_data_5_RVALID
    | _selectedMatrixRResp_T_6 & m_axi_Matrix_data_6_RVALID | (&matrixIndex)
    & m_axi_Matrix_data_7_RVALID;
  wire         _GEN = statusIndex == 5'hF;
  wire         _GEN_0 = metricIndex == 5'hF;
  wire         _GEN_1 = state == 4'h1;
  wire         _GEN_2 = state == 4'h2;
  wire         _GEN_3 = ~(|state) | _GEN_1;
  wire         _GEN_4 = state == 4'h3;
  wire         _GEN_5 = ~(|state) | _GEN_1 | _GEN_2;
  wire         _GEN_6 = state == 4'h4;
  wire         _GEN_7 = _GEN_1 | _GEN_2 | _GEN_4;
  wire         _GEN_8 = ~(|state) | _GEN_7;
  wire         _GEN_9 = state == 4'h5;
  wire         _GEN_10 = ~(|state) | _GEN_1 | _GEN_2 | _GEN_4 | _GEN_6;
  wire         _GEN_11 = state == 4'h6;
  wire         _GEN_12 = ~(|state) | _GEN_1 | _GEN_2 | _GEN_4 | _GEN_6 | _GEN_9;
  wire         _GEN_13 = state == 4'h7;
  wire         _GEN_14 = ~(|state) | _GEN_1 | _GEN_2 | _GEN_4 | _GEN_6 | _GEN_9 | _GEN_11;
  wire         _GEN_15 = state == 4'h8;
  wire         _GEN_16 = state == 4'h9;
  wire         _GEN_17 =
    ~(|state) | _GEN_1 | _GEN_2 | _GEN_4 | _GEN_6 | _GEN_9 | _GEN_11 | _GEN_13 | _GEN_15;
  wire         _GEN_18 = state == 4'hA;
  wire         _GEN_19 =
    ~(|state) | _GEN_1 | _GEN_2 | _GEN_4 | _GEN_6 | _GEN_9 | _GEN_11 | _GEN_13 | _GEN_15
    | _GEN_16;
  wire         _GEN_20 = state == 4'hB;
  wire         _GEN_21 =
    ~(|state) | _GEN_1 | _GEN_2 | _GEN_4 | _GEN_6 | _GEN_9 | _GEN_11 | _GEN_13 | _GEN_15
    | _GEN_16 | _GEN_18;
  wire         _GEN_22 = state == 4'hC;
  wire         _GEN_23 = _GEN_18 | _GEN_20;
  wire         _GEN_24 =
    _GEN_1 | _GEN_2 | _GEN_4 | _GEN_6 | _GEN_9 | _GEN_11 | _GEN_13 | _GEN_15 | _GEN_16
    | _GEN_23;
  wire         _GEN_25 = state == 4'hD;
  wire         _GEN_26 =
    ~(|state) | _GEN_1 | _GEN_2 | _GEN_4 | _GEN_6 | _GEN_9 | _GEN_11 | _GEN_13 | _GEN_15
    | _GEN_16 | _GEN_18 | _GEN_20 | _GEN_22;
  wire         _GEN_27 = state == 4'hE;
  wire         _GEN_28 =
    ~(|state) | _GEN_1 | _GEN_2 | _GEN_4 | _GEN_6 | _GEN_9 | _GEN_11 | _GEN_13 | _GEN_15
    | _GEN_16 | _GEN_18 | _GEN_20 | _GEN_22 | _GEN_25;
  reg  [3:0]   casez_tmp;
  wire [3:0]   _GEN_29 = _GEN_27 & m_axi_Metrics_WREADY ? 4'hF : state;
  always @(*) begin
    casez (state)
      4'b0000:
        casez_tmp = _GEN_29;
      4'b0001:
        casez_tmp = m_axi_SpElement_list_ptr_ARREADY ? 4'h2 : state;
      4'b0010:
        casez_tmp = m_axi_SpElement_list_ptr_RVALID ? 4'h3 : state;
      4'b0011:
        casez_tmp =
          ~(|matrixIndex) & m_axi_Matrix_data_0_ARREADY | _selectedMatrixRResp_T_1
          & m_axi_Matrix_data_1_ARREADY | _selectedMatrixRResp_T_2
          & m_axi_Matrix_data_2_ARREADY | _selectedMatrixRResp_T_3
          & m_axi_Matrix_data_3_ARREADY | _selectedMatrixRResp_T_4
          & m_axi_Matrix_data_4_ARREADY | _selectedMatrixRResp_T_5
          & m_axi_Matrix_data_5_ARREADY | _selectedMatrixRResp_T_6
          & m_axi_Matrix_data_6_ARREADY | (&matrixIndex) & m_axi_Matrix_data_7_ARREADY
            ? 4'h4
            : state;
      4'b0100:
        casez_tmp = selectedMatrixRValid ? ((&matrixIndex) ? 4'h5 : 4'h3) : state;
      4'b0101:
        casez_tmp = m_axi_X_ARREADY ? 4'h6 : state;
      4'b0110:
        casez_tmp = m_axi_X_RVALID ? 4'h7 : state;
      4'b0111:
        casez_tmp = m_axi_Y_out_AWREADY ? 4'h8 : state;
      4'b1000:
        casez_tmp = m_axi_Y_out_WREADY ? 4'h9 : state;
      4'b1001:
        casez_tmp = m_axi_Y_out_BVALID ? 4'hA : state;
      4'b1010:
        casez_tmp = m_axi_Status_AWREADY ? 4'hB : state;
      4'b1011:
        casez_tmp = m_axi_Status_WREADY ? 4'hC : state;
      4'b1100:
        casez_tmp = m_axi_Status_BVALID ? (_GEN ? 4'hD : 4'hA) : state;
      4'b1101:
        casez_tmp = m_axi_Metrics_AWREADY ? 4'hE : state;
      4'b1110:
        casez_tmp = _GEN_29;
      default:
        casez_tmp = _GEN_29;
    endcase
  end // always
  wire [2:0]   unusedRespIds =
    {m_axi_SpElement_list_ptr_RID,
     m_axi_SpElement_list_ptr_BID,
     m_axi_SpElement_list_ptr_RLAST}
    ^ {m_axi_Matrix_data_0_RID, m_axi_Matrix_data_0_BID, m_axi_Matrix_data_0_RLAST}
    ^ {m_axi_Matrix_data_1_RID, m_axi_Matrix_data_1_BID, m_axi_Matrix_data_1_RLAST}
    ^ {m_axi_Matrix_data_2_RID, m_axi_Matrix_data_2_BID, m_axi_Matrix_data_2_RLAST}
    ^ {m_axi_Matrix_data_3_RID, m_axi_Matrix_data_3_BID, m_axi_Matrix_data_3_RLAST}
    ^ {m_axi_Matrix_data_4_RID, m_axi_Matrix_data_4_BID, m_axi_Matrix_data_4_RLAST}
    ^ {m_axi_Matrix_data_5_RID, m_axi_Matrix_data_5_BID, m_axi_Matrix_data_5_RLAST}
    ^ {m_axi_Matrix_data_6_RID, m_axi_Matrix_data_6_BID, m_axi_Matrix_data_6_RLAST}
    ^ {m_axi_Matrix_data_7_RID, m_axi_Matrix_data_7_BID, m_axi_Matrix_data_7_RLAST}
    ^ {m_axi_X_RID, m_axi_X_BID, m_axi_X_RLAST}
    ^ {m_axi_Y_out_RID, m_axi_Y_out_BID, m_axi_Y_out_RLAST}
    ^ {m_axi_Status_RID, m_axi_Status_BID, m_axi_Status_RLAST}
    ^ {m_axi_Metrics_RID, m_axi_Metrics_BID, m_axi_Metrics_RLAST};
  wire         _rIsCtrl_T = s_axi_control_ARADDR == 12'h0;
  wire         commitWrite = awValid & wValid & ~bValid;
  wire         _GEN_30 = awAddr == 12'h0;
  wire         _GEN_31 = commitWrite & _GEN_30 & wData[0];
  wire         _GEN_32 = awAddr == 12'h10;
  wire         _GEN_33 = awAddr == 12'h14;
  wire         _GEN_34 = awAddr == 12'h1C;
  wire         _GEN_35 = awAddr == 12'h20;
  wire         _GEN_36 = awAddr == 12'h28;
  wire         _GEN_37 = awAddr == 12'h2C;
  wire         _GEN_38 = awAddr == 12'h34;
  wire         _GEN_39 = awAddr == 12'h38;
  wire         _GEN_40 = awAddr == 12'h40;
  wire         _GEN_41 = awAddr == 12'h44;
  wire         _GEN_42 = awAddr == 12'h4C;
  wire         _GEN_43 = awAddr == 12'h50;
  wire         _GEN_44 = awAddr == 12'h58;
  wire         _GEN_45 = awAddr == 12'h5C;
  wire         _GEN_46 = awAddr == 12'h64;
  wire         _GEN_47 = awAddr == 12'h68;
  wire         _GEN_48 = awAddr == 12'h70;
  wire         _GEN_49 = awAddr == 12'h74;
  wire         _GEN_50 = awAddr == 12'h7C;
  wire         _GEN_51 = awAddr == 12'h80;
  wire         _GEN_52 = awAddr == 12'h88;
  wire         _GEN_53 = awAddr == 12'h8C;
  wire         _GEN_54 = awAddr == 12'h94;
  wire         _GEN_55 = awAddr == 12'h98;
  wire         _GEN_56 = awAddr == 12'hA0;
  wire         _GEN_57 = awAddr == 12'hA4;
  wire         _GEN_58 = awAddr == 12'hAC;
  wire         _GEN_59 = awAddr == 12'hB4;
  wire         _GEN_60 = awAddr == 12'hBC;
  wire         _GEN_61 = awAddr == 12'hC4;
  wire         _GEN_62 = ~rValid & s_axi_control_ARVALID;
  wire         _GEN_63 = rValid & s_axi_control_RREADY;
  wire [511:0] selectedMatrixRData =
    ((|matrixIndex) ? 512'h0 : m_axi_Matrix_data_0_RDATA)
    | (_selectedMatrixRResp_T_1 ? m_axi_Matrix_data_1_RDATA : 512'h0)
    | (_selectedMatrixRResp_T_2 ? m_axi_Matrix_data_2_RDATA : 512'h0)
    | (_selectedMatrixRResp_T_3 ? m_axi_Matrix_data_3_RDATA : 512'h0)
    | (_selectedMatrixRResp_T_4 ? m_axi_Matrix_data_4_RDATA : 512'h0)
    | (_selectedMatrixRResp_T_5 ? m_axi_Matrix_data_5_RDATA : 512'h0)
    | (_selectedMatrixRResp_T_6 ? m_axi_Matrix_data_6_RDATA : 512'h0)
    | ((&matrixIndex) ? m_axi_Matrix_data_7_RDATA : 512'h0);
  wire         _GEN_64 = ~(|state) & startPending;
  wire         _GEN_65 = _GEN_11 & m_axi_X_RVALID;
  wire         _GEN_66 = _GEN_22 & m_axi_Status_BVALID;
  wire         _GEN_67 = (&state) & m_axi_Metrics_BVALID;
  wire         _GEN_68 = ~awValid & s_axi_control_AWVALID;
  wire         _GEN_69 = ~wValid & s_axi_control_WVALID;
  always @(posedge ap_clk) begin
    if (~ap_rst_n) begin
      argPtr_0 <= 64'h0;
      argPtr_1 <= 64'h0;
      argPtr_2 <= 64'h0;
      argPtr_3 <= 64'h0;
      argPtr_4 <= 64'h0;
      argPtr_5 <= 64'h0;
      argPtr_6 <= 64'h0;
      argPtr_7 <= 64'h0;
      argPtr_8 <= 64'h0;
      argPtr_9 <= 64'h0;
      argPtr_10 <= 64'h0;
      argPtr_11 <= 64'h0;
      argPtr_12 <= 64'h0;
      batchNum <= 32'h0;
      matrixLen <= 32'h0;
      rowNum <= 32'h0;
      columnNum <= 32'h0;
      iterationNum <= 32'h0;
      startPending <= 1'h0;
      autoRestart <= 1'h0;
      doneSticky <= 1'h0;
      awValid <= 1'h0;
      wValid <= 1'h0;
      bValid <= 1'h0;
      state <= 4'h0;
      matrixIndex <= 3'h0;
      statusIndex <= 5'h0;
      metricIndex <= 5'h0;
      ptr0 <= 32'h0;
      x0 <= 512'h0;
      matrixFirst_0 <= 512'h0;
      matrixFirst_1 <= 512'h0;
      matrixFirst_2 <= 512'h0;
      matrixFirst_3 <= 512'h0;
      matrixFirst_4 <= 512'h0;
      matrixFirst_5 <= 512'h0;
      matrixFirst_6 <= 512'h0;
      matrixFirst_7 <= 512'h0;
      cycleCounter <= 64'h0;
      lastBresp <= 2'h0;
      lastRresp <= 2'h0;
      rValid <= 1'h0;
      rData <= 32'h0;
      rIsCtrl <= 1'h0;
    end
    else begin
      if (~commitWrite | _GEN_30) begin
      end
      else if (_GEN_32)
        argPtr_0 <= {argPtr_0[63:32], wData};
      else if (_GEN_33)
        argPtr_0 <= {wData, argPtr_0[31:0]};
      if (~commitWrite | _GEN_30 | _GEN_32 | _GEN_33) begin
      end
      else if (_GEN_34)
        argPtr_1 <= {argPtr_1[63:32], wData};
      else if (_GEN_35)
        argPtr_1 <= {wData, argPtr_1[31:0]};
      if (~commitWrite | _GEN_30 | _GEN_32 | _GEN_33 | _GEN_34 | _GEN_35) begin
      end
      else if (_GEN_36)
        argPtr_2 <= {argPtr_2[63:32], wData};
      else if (_GEN_37)
        argPtr_2 <= {wData, argPtr_2[31:0]};
      if (~commitWrite | _GEN_30 | _GEN_32 | _GEN_33 | _GEN_34 | _GEN_35 | _GEN_36
          | _GEN_37) begin
      end
      else if (_GEN_38)
        argPtr_3 <= {argPtr_3[63:32], wData};
      else if (_GEN_39)
        argPtr_3 <= {wData, argPtr_3[31:0]};
      if (~commitWrite | _GEN_30 | _GEN_32 | _GEN_33 | _GEN_34 | _GEN_35 | _GEN_36
          | _GEN_37 | _GEN_38 | _GEN_39) begin
      end
      else if (_GEN_40)
        argPtr_4 <= {argPtr_4[63:32], wData};
      else if (_GEN_41)
        argPtr_4 <= {wData, argPtr_4[31:0]};
      if (~commitWrite | _GEN_30 | _GEN_32 | _GEN_33 | _GEN_34 | _GEN_35 | _GEN_36
          | _GEN_37 | _GEN_38 | _GEN_39 | _GEN_40 | _GEN_41) begin
      end
      else if (_GEN_42)
        argPtr_5 <= {argPtr_5[63:32], wData};
      else if (_GEN_43)
        argPtr_5 <= {wData, argPtr_5[31:0]};
      if (~commitWrite | _GEN_30 | _GEN_32 | _GEN_33 | _GEN_34 | _GEN_35 | _GEN_36
          | _GEN_37 | _GEN_38 | _GEN_39 | _GEN_40 | _GEN_41 | _GEN_42 | _GEN_43) begin
      end
      else if (_GEN_44)
        argPtr_6 <= {argPtr_6[63:32], wData};
      else if (_GEN_45)
        argPtr_6 <= {wData, argPtr_6[31:0]};
      if (~commitWrite | _GEN_30 | _GEN_32 | _GEN_33 | _GEN_34 | _GEN_35 | _GEN_36
          | _GEN_37 | _GEN_38 | _GEN_39 | _GEN_40 | _GEN_41 | _GEN_42 | _GEN_43 | _GEN_44
          | _GEN_45) begin
      end
      else if (_GEN_46)
        argPtr_7 <= {argPtr_7[63:32], wData};
      else if (_GEN_47)
        argPtr_7 <= {wData, argPtr_7[31:0]};
      if (~commitWrite | _GEN_30 | _GEN_32 | _GEN_33 | _GEN_34 | _GEN_35 | _GEN_36
          | _GEN_37 | _GEN_38 | _GEN_39 | _GEN_40 | _GEN_41 | _GEN_42 | _GEN_43 | _GEN_44
          | _GEN_45 | _GEN_46 | _GEN_47) begin
      end
      else if (_GEN_48)
        argPtr_8 <= {argPtr_8[63:32], wData};
      else if (_GEN_49)
        argPtr_8 <= {wData, argPtr_8[31:0]};
      if (~commitWrite | _GEN_30 | _GEN_32 | _GEN_33 | _GEN_34 | _GEN_35 | _GEN_36
          | _GEN_37 | _GEN_38 | _GEN_39 | _GEN_40 | _GEN_41 | _GEN_42 | _GEN_43 | _GEN_44
          | _GEN_45 | _GEN_46 | _GEN_47 | _GEN_48 | _GEN_49) begin
      end
      else if (_GEN_50)
        argPtr_9 <= {argPtr_9[63:32], wData};
      else if (_GEN_51)
        argPtr_9 <= {wData, argPtr_9[31:0]};
      if (~commitWrite | _GEN_30 | _GEN_32 | _GEN_33 | _GEN_34 | _GEN_35 | _GEN_36
          | _GEN_37 | _GEN_38 | _GEN_39 | _GEN_40 | _GEN_41 | _GEN_42 | _GEN_43 | _GEN_44
          | _GEN_45 | _GEN_46 | _GEN_47 | _GEN_48 | _GEN_49 | _GEN_50 | _GEN_51) begin
      end
      else if (_GEN_52)
        argPtr_10 <= {argPtr_10[63:32], wData};
      else if (_GEN_53)
        argPtr_10 <= {wData, argPtr_10[31:0]};
      if (~commitWrite | _GEN_30 | _GEN_32 | _GEN_33 | _GEN_34 | _GEN_35 | _GEN_36
          | _GEN_37 | _GEN_38 | _GEN_39 | _GEN_40 | _GEN_41 | _GEN_42 | _GEN_43 | _GEN_44
          | _GEN_45 | _GEN_46 | _GEN_47 | _GEN_48 | _GEN_49 | _GEN_50 | _GEN_51 | _GEN_52
          | _GEN_53) begin
      end
      else if (_GEN_54)
        argPtr_11 <= {argPtr_11[63:32], wData};
      else if (_GEN_55)
        argPtr_11 <= {wData, argPtr_11[31:0]};
      if (~commitWrite | _GEN_30 | _GEN_32 | _GEN_33 | _GEN_34 | _GEN_35 | _GEN_36
          | _GEN_37 | _GEN_38 | _GEN_39 | _GEN_40 | _GEN_41 | _GEN_42 | _GEN_43 | _GEN_44
          | _GEN_45 | _GEN_46 | _GEN_47 | _GEN_48 | _GEN_49 | _GEN_50 | _GEN_51 | _GEN_52
          | _GEN_53 | _GEN_54 | _GEN_55) begin
      end
      else if (_GEN_56)
        argPtr_12 <= {argPtr_12[63:32], wData};
      else if (_GEN_57)
        argPtr_12 <= {wData, argPtr_12[31:0]};
      if (~commitWrite | _GEN_30 | _GEN_32 | _GEN_33 | _GEN_34 | _GEN_35 | _GEN_36
          | _GEN_37 | _GEN_38 | _GEN_39 | _GEN_40 | _GEN_41 | _GEN_42 | _GEN_43 | _GEN_44
          | _GEN_45 | _GEN_46 | _GEN_47 | _GEN_48 | _GEN_49 | _GEN_50 | _GEN_51 | _GEN_52
          | _GEN_53 | _GEN_54 | _GEN_55 | _GEN_56 | _GEN_57 | ~_GEN_58) begin
      end
      else
        batchNum <= wData;
      if (~commitWrite | _GEN_30 | _GEN_32 | _GEN_33 | _GEN_34 | _GEN_35 | _GEN_36
          | _GEN_37 | _GEN_38 | _GEN_39 | _GEN_40 | _GEN_41 | _GEN_42 | _GEN_43 | _GEN_44
          | _GEN_45 | _GEN_46 | _GEN_47 | _GEN_48 | _GEN_49 | _GEN_50 | _GEN_51 | _GEN_52
          | _GEN_53 | _GEN_54 | _GEN_55 | _GEN_56 | _GEN_57 | _GEN_58 | ~_GEN_59) begin
      end
      else
        matrixLen <= wData;
      if (~commitWrite | _GEN_30 | _GEN_32 | _GEN_33 | _GEN_34 | _GEN_35 | _GEN_36
          | _GEN_37 | _GEN_38 | _GEN_39 | _GEN_40 | _GEN_41 | _GEN_42 | _GEN_43 | _GEN_44
          | _GEN_45 | _GEN_46 | _GEN_47 | _GEN_48 | _GEN_49 | _GEN_50 | _GEN_51 | _GEN_52
          | _GEN_53 | _GEN_54 | _GEN_55 | _GEN_56 | _GEN_57 | _GEN_58 | _GEN_59
          | ~_GEN_60) begin
      end
      else
        rowNum <= wData;
      if (~commitWrite | _GEN_30 | _GEN_32 | _GEN_33 | _GEN_34 | _GEN_35 | _GEN_36
          | _GEN_37 | _GEN_38 | _GEN_39 | _GEN_40 | _GEN_41 | _GEN_42 | _GEN_43 | _GEN_44
          | _GEN_45 | _GEN_46 | _GEN_47 | _GEN_48 | _GEN_49 | _GEN_50 | _GEN_51 | _GEN_52
          | _GEN_53 | _GEN_54 | _GEN_55 | _GEN_56 | _GEN_57 | _GEN_58 | _GEN_59 | _GEN_60
          | ~_GEN_61) begin
      end
      else
        columnNum <= wData;
      if (~commitWrite | _GEN_30 | _GEN_32 | _GEN_33 | _GEN_34 | _GEN_35 | _GEN_36
          | _GEN_37 | _GEN_38 | _GEN_39 | _GEN_40 | _GEN_41 | _GEN_42 | _GEN_43 | _GEN_44
          | _GEN_45 | _GEN_46 | _GEN_47 | _GEN_48 | _GEN_49 | _GEN_50 | _GEN_51 | _GEN_52
          | _GEN_53 | _GEN_54 | _GEN_55 | _GEN_56 | _GEN_57 | _GEN_58 | _GEN_59 | _GEN_60
          | _GEN_61 | awAddr != 12'hCC) begin
      end
      else
        iterationNum <= wData;
      startPending <=
        (&state) & m_axi_Metrics_BVALID & _GEN_0 & autoRestart | ~_GEN_64
        & (_GEN_31 | startPending);
      if (commitWrite & _GEN_30)
        autoRestart <= wData[7];
      doneSticky <=
        (&state) & m_axi_Metrics_BVALID & _GEN_0 | ~_GEN_64
        & (_GEN_63 ? ~(rIsCtrl | _GEN_31) & doneSticky : ~_GEN_31 & doneSticky);
      awValid <= ~commitWrite & (_GEN_68 | awValid);
      wValid <= ~commitWrite & (_GEN_69 | wValid);
      bValid <= ~(bValid & s_axi_control_BREADY) & (commitWrite | bValid);
      if (_GEN_67) begin
        state <= _GEN_0 ? 4'h0 : 4'hD;
        lastBresp <= m_axi_Metrics_BRESP;
      end
      else begin
        if (|state)
          state <= casez_tmp;
        else if (startPending)
          state <= 4'h1;
        if (~_GEN_17) begin
          if (_GEN_16) begin
            if (m_axi_Y_out_BVALID)
              lastBresp <= m_axi_Y_out_BRESP;
          end
          else if (_GEN_23 | ~_GEN_66) begin
          end
          else
            lastBresp <= m_axi_Status_BRESP;
        end
      end
      if (|state) begin
        if (_GEN_7 | ~(_GEN_6 & selectedMatrixRValid) | (&matrixIndex)) begin
        end
        else
          matrixIndex <= matrixIndex + 3'h1;
        if (_GEN_24 | ~_GEN_66 | _GEN) begin
        end
        else
          statusIndex <= statusIndex + 5'h1;
      end
      else if (startPending) begin
        matrixIndex <= 3'h0;
        statusIndex <= 5'h0;
      end
      if (~_GEN_67 | _GEN_0) begin
        if (|state) begin
          if (_GEN_24 | ~(_GEN_22 & m_axi_Status_BVALID & _GEN)) begin
          end
          else
            metricIndex <= 5'h0;
        end
        else if (startPending)
          metricIndex <= 5'h0;
      end
      else
        metricIndex <= metricIndex + 5'h1;
      if (_GEN_3 | ~(_GEN_2 & m_axi_SpElement_list_ptr_RVALID)) begin
      end
      else
        ptr0 <= m_axi_SpElement_list_ptr_RDATA;
      if (_GEN_12 | ~_GEN_65) begin
      end
      else
        x0 <= m_axi_X_RDATA;
      if (_GEN_8 | ~(_GEN_6 & selectedMatrixRValid & ~(|matrixIndex))) begin
      end
      else
        matrixFirst_0 <= selectedMatrixRData;
      if (_GEN_8 | ~(_GEN_6 & selectedMatrixRValid & matrixIndex == 3'h1)) begin
      end
      else
        matrixFirst_1 <= selectedMatrixRData;
      if (_GEN_8 | ~(_GEN_6 & selectedMatrixRValid & matrixIndex == 3'h2)) begin
      end
      else
        matrixFirst_2 <= selectedMatrixRData;
      if (_GEN_8 | ~(_GEN_6 & selectedMatrixRValid & matrixIndex == 3'h3)) begin
      end
      else
        matrixFirst_3 <= selectedMatrixRData;
      if (_GEN_8 | ~(_GEN_6 & selectedMatrixRValid & matrixIndex == 3'h4)) begin
      end
      else
        matrixFirst_4 <= selectedMatrixRData;
      if (_GEN_8 | ~(_GEN_6 & selectedMatrixRValid & matrixIndex == 3'h5)) begin
      end
      else
        matrixFirst_5 <= selectedMatrixRData;
      if (_GEN_8 | ~(_GEN_6 & selectedMatrixRValid & matrixIndex == 3'h6)) begin
      end
      else
        matrixFirst_6 <= selectedMatrixRData;
      if (_GEN_8 | ~(_GEN_6 & selectedMatrixRValid & (&matrixIndex))) begin
      end
      else
        matrixFirst_7 <= selectedMatrixRData;
      if (_GEN_64)
        cycleCounter <= 64'h0;
      else if (|state)
        cycleCounter <= cycleCounter + 64'h1;
      if (~_GEN_3) begin
        if (_GEN_2) begin
          if (m_axi_SpElement_list_ptr_RVALID)
            lastRresp <= m_axi_SpElement_list_ptr_RRESP;
        end
        else if (~_GEN_4) begin
          if (_GEN_6) begin
            if (selectedMatrixRValid)
              lastRresp <=
                ((|matrixIndex) ? 2'h0 : m_axi_Matrix_data_0_RRESP)
                | (_selectedMatrixRResp_T_1 ? m_axi_Matrix_data_1_RRESP : 2'h0)
                | (_selectedMatrixRResp_T_2 ? m_axi_Matrix_data_2_RRESP : 2'h0)
                | (_selectedMatrixRResp_T_3 ? m_axi_Matrix_data_3_RRESP : 2'h0)
                | (_selectedMatrixRResp_T_4 ? m_axi_Matrix_data_4_RRESP : 2'h0)
                | (_selectedMatrixRResp_T_5 ? m_axi_Matrix_data_5_RRESP : 2'h0)
                | (_selectedMatrixRResp_T_6 ? m_axi_Matrix_data_6_RRESP : 2'h0)
                | ((&matrixIndex) ? m_axi_Matrix_data_7_RRESP : 2'h0);
          end
          else if (_GEN_9 | ~_GEN_65) begin
          end
          else
            lastRresp <= m_axi_X_RRESP;
        end
      end
      rValid <= ~_GEN_63 & (_GEN_62 | rValid);
      if (_GEN_62) begin
        rData <=
          _rIsCtrl_T
            ? {24'h0, autoRestart, 3'h0, doneSticky, ~(|state), doneSticky, startPending}
            : s_axi_control_ARADDR == 12'h10
                ? argPtr_0[31:0]
                : s_axi_control_ARADDR == 12'h14
                    ? argPtr_0[63:32]
                    : s_axi_control_ARADDR == 12'h1C
                        ? argPtr_1[31:0]
                        : s_axi_control_ARADDR == 12'h20
                            ? argPtr_1[63:32]
                            : s_axi_control_ARADDR == 12'h28
                                ? argPtr_2[31:0]
                                : s_axi_control_ARADDR == 12'h2C
                                    ? argPtr_2[63:32]
                                    : s_axi_control_ARADDR == 12'h34
                                        ? argPtr_3[31:0]
                                        : s_axi_control_ARADDR == 12'h38
                                            ? argPtr_3[63:32]
                                            : s_axi_control_ARADDR == 12'h40
                                                ? argPtr_4[31:0]
                                                : s_axi_control_ARADDR == 12'h44
                                                    ? argPtr_4[63:32]
                                                    : s_axi_control_ARADDR == 12'h4C
                                                        ? argPtr_5[31:0]
                                                        : s_axi_control_ARADDR == 12'h50
                                                            ? argPtr_5[63:32]
                                                            : s_axi_control_ARADDR == 12'h58
                                                                ? argPtr_6[31:0]
                                                                : s_axi_control_ARADDR == 12'h5C
                                                                    ? argPtr_6[63:32]
                                                                    : s_axi_control_ARADDR == 12'h64
                                                                        ? argPtr_7[31:0]
                                                                        : s_axi_control_ARADDR == 12'h68
                                                                            ? argPtr_7[63:32]
                                                                            : s_axi_control_ARADDR == 12'h70
                                                                                ? argPtr_8[31:0]
                                                                                : s_axi_control_ARADDR == 12'h74
                                                                                    ? argPtr_8[63:32]
                                                                                    : s_axi_control_ARADDR == 12'h7C
                                                                                        ? argPtr_9[31:0]
                                                                                        : s_axi_control_ARADDR == 12'h80
                                                                                            ? argPtr_9[63:32]
                                                                                            : s_axi_control_ARADDR == 12'h88
                                                                                                ? argPtr_10[31:0]
                                                                                                : s_axi_control_ARADDR == 12'h8C
                                                                                                    ? argPtr_10[63:32]
                                                                                                    : s_axi_control_ARADDR == 12'h94
                                                                                                        ? argPtr_11[31:0]
                                                                                                        : s_axi_control_ARADDR == 12'h98
                                                                                                            ? argPtr_11[63:32]
                                                                                                            : s_axi_control_ARADDR == 12'hA0
                                                                                                                ? argPtr_12[31:0]
                                                                                                                : s_axi_control_ARADDR == 12'hA4
                                                                                                                    ? argPtr_12[63:32]
                                                                                                                    : s_axi_control_ARADDR == 12'hAC
                                                                                                                        ? batchNum
                                                                                                                        : s_axi_control_ARADDR == 12'hB4
                                                                                                                            ? matrixLen
                                                                                                                            : s_axi_control_ARADDR == 12'hBC
                                                                                                                                ? rowNum
                                                                                                                                : s_axi_control_ARADDR == 12'hC4
                                                                                                                                    ? columnNum
                                                                                                                                    : s_axi_control_ARADDR == 12'hCC
                                                                                                                                        ? iterationNum
                                                                                                                                        : 32'h0;
        rIsCtrl <= _rIsCtrl_T;
      end
    end
    if (_GEN_68)
      awAddr <= s_axi_control_AWADDR;
    if (_GEN_69) begin
      wData <= s_axi_control_WDATA;
      wStrb <= s_axi_control_WSTRB;
    end
  end // always @(posedge)
  assign interrupt = doneSticky;
  assign s_axi_control_AWREADY = ~awValid;
  assign s_axi_control_WREADY = ~wValid;
  assign s_axi_control_ARREADY = ~rValid;
  assign s_axi_control_RVALID = rValid;
  assign s_axi_control_RDATA = rData;
  assign s_axi_control_RRESP = 2'h0;
  assign s_axi_control_BVALID = bValid;
  assign s_axi_control_BRESP = 2'h0;
  assign m_axi_SpElement_list_ptr_AWADDR = 64'h0;
  assign m_axi_SpElement_list_ptr_AWBURST = 2'h1;
  assign m_axi_SpElement_list_ptr_AWCACHE = 4'h3;
  assign m_axi_SpElement_list_ptr_AWID = 1'h0;
  assign m_axi_SpElement_list_ptr_AWLEN = 8'h0;
  assign m_axi_SpElement_list_ptr_AWLOCK = 1'h0;
  assign m_axi_SpElement_list_ptr_AWPROT = 3'h0;
  assign m_axi_SpElement_list_ptr_AWQOS = 4'h0;
  assign m_axi_SpElement_list_ptr_AWSIZE = 3'h2;
  assign m_axi_SpElement_list_ptr_AWVALID = 1'h0;
  assign m_axi_SpElement_list_ptr_BREADY = 1'h0;
  assign m_axi_SpElement_list_ptr_ARADDR = (|state) & _GEN_1 ? argPtr_0 : 64'h0;
  assign m_axi_SpElement_list_ptr_ARBURST = 2'h1;
  assign m_axi_SpElement_list_ptr_ARCACHE = 4'h3;
  assign m_axi_SpElement_list_ptr_ARID = 1'h0;
  assign m_axi_SpElement_list_ptr_ARLEN = 8'h0;
  assign m_axi_SpElement_list_ptr_ARLOCK = 1'h0;
  assign m_axi_SpElement_list_ptr_ARPROT = 3'h0;
  assign m_axi_SpElement_list_ptr_ARQOS = 4'h0;
  assign m_axi_SpElement_list_ptr_ARSIZE = 3'h2;
  assign m_axi_SpElement_list_ptr_ARVALID = (|state) & _GEN_1;
  assign m_axi_SpElement_list_ptr_RREADY = ~_GEN_3 & _GEN_2;
  assign m_axi_SpElement_list_ptr_WDATA = 32'h0;
  assign m_axi_SpElement_list_ptr_WLAST = 1'h1;
  assign m_axi_SpElement_list_ptr_WSTRB = 4'hF;
  assign m_axi_SpElement_list_ptr_WVALID = 1'h0;
  assign m_axi_Matrix_data_0_AWADDR = 64'h0;
  assign m_axi_Matrix_data_0_AWBURST = 2'h1;
  assign m_axi_Matrix_data_0_AWCACHE = 4'h3;
  assign m_axi_Matrix_data_0_AWID = 1'h0;
  assign m_axi_Matrix_data_0_AWLEN = 8'h0;
  assign m_axi_Matrix_data_0_AWLOCK = 1'h0;
  assign m_axi_Matrix_data_0_AWPROT = 3'h0;
  assign m_axi_Matrix_data_0_AWQOS = 4'h0;
  assign m_axi_Matrix_data_0_AWSIZE = 3'h6;
  assign m_axi_Matrix_data_0_AWVALID = 1'h0;
  assign m_axi_Matrix_data_0_BREADY = 1'h0;
  assign m_axi_Matrix_data_0_ARADDR =
    _GEN_5 | ~(_GEN_4 & ~(|matrixIndex)) ? 64'h0 : argPtr_1;
  assign m_axi_Matrix_data_0_ARBURST = 2'h1;
  assign m_axi_Matrix_data_0_ARCACHE = 4'h3;
  assign m_axi_Matrix_data_0_ARID = 1'h0;
  assign m_axi_Matrix_data_0_ARLEN = 8'h0;
  assign m_axi_Matrix_data_0_ARLOCK = 1'h0;
  assign m_axi_Matrix_data_0_ARPROT = 3'h0;
  assign m_axi_Matrix_data_0_ARQOS = 4'h0;
  assign m_axi_Matrix_data_0_ARSIZE = 3'h6;
  assign m_axi_Matrix_data_0_ARVALID = ~_GEN_5 & _GEN_4 & ~(|matrixIndex);
  assign m_axi_Matrix_data_0_RREADY = ~_GEN_8 & _GEN_6 & ~(|matrixIndex);
  assign m_axi_Matrix_data_0_WDATA = 512'h0;
  assign m_axi_Matrix_data_0_WLAST = 1'h1;
  assign m_axi_Matrix_data_0_WSTRB = 64'hFFFFFFFFFFFFFFFF;
  assign m_axi_Matrix_data_0_WVALID = 1'h0;
  assign m_axi_Matrix_data_1_AWADDR = 64'h0;
  assign m_axi_Matrix_data_1_AWBURST = 2'h1;
  assign m_axi_Matrix_data_1_AWCACHE = 4'h3;
  assign m_axi_Matrix_data_1_AWID = 1'h0;
  assign m_axi_Matrix_data_1_AWLEN = 8'h0;
  assign m_axi_Matrix_data_1_AWLOCK = 1'h0;
  assign m_axi_Matrix_data_1_AWPROT = 3'h0;
  assign m_axi_Matrix_data_1_AWQOS = 4'h0;
  assign m_axi_Matrix_data_1_AWSIZE = 3'h6;
  assign m_axi_Matrix_data_1_AWVALID = 1'h0;
  assign m_axi_Matrix_data_1_BREADY = 1'h0;
  assign m_axi_Matrix_data_1_ARADDR =
    _GEN_5 | ~(_GEN_4 & _selectedMatrixRResp_T_1) ? 64'h0 : argPtr_2;
  assign m_axi_Matrix_data_1_ARBURST = 2'h1;
  assign m_axi_Matrix_data_1_ARCACHE = 4'h3;
  assign m_axi_Matrix_data_1_ARID = 1'h0;
  assign m_axi_Matrix_data_1_ARLEN = 8'h0;
  assign m_axi_Matrix_data_1_ARLOCK = 1'h0;
  assign m_axi_Matrix_data_1_ARPROT = 3'h0;
  assign m_axi_Matrix_data_1_ARQOS = 4'h0;
  assign m_axi_Matrix_data_1_ARSIZE = 3'h6;
  assign m_axi_Matrix_data_1_ARVALID = ~_GEN_5 & _GEN_4 & _selectedMatrixRResp_T_1;
  assign m_axi_Matrix_data_1_RREADY = ~_GEN_8 & _GEN_6 & _selectedMatrixRResp_T_1;
  assign m_axi_Matrix_data_1_WDATA = 512'h0;
  assign m_axi_Matrix_data_1_WLAST = 1'h1;
  assign m_axi_Matrix_data_1_WSTRB = 64'hFFFFFFFFFFFFFFFF;
  assign m_axi_Matrix_data_1_WVALID = 1'h0;
  assign m_axi_Matrix_data_2_AWADDR = 64'h0;
  assign m_axi_Matrix_data_2_AWBURST = 2'h1;
  assign m_axi_Matrix_data_2_AWCACHE = 4'h3;
  assign m_axi_Matrix_data_2_AWID = 1'h0;
  assign m_axi_Matrix_data_2_AWLEN = 8'h0;
  assign m_axi_Matrix_data_2_AWLOCK = 1'h0;
  assign m_axi_Matrix_data_2_AWPROT = 3'h0;
  assign m_axi_Matrix_data_2_AWQOS = 4'h0;
  assign m_axi_Matrix_data_2_AWSIZE = 3'h6;
  assign m_axi_Matrix_data_2_AWVALID = 1'h0;
  assign m_axi_Matrix_data_2_BREADY = 1'h0;
  assign m_axi_Matrix_data_2_ARADDR =
    _GEN_5 | ~(_GEN_4 & _selectedMatrixRResp_T_2) ? 64'h0 : argPtr_3;
  assign m_axi_Matrix_data_2_ARBURST = 2'h1;
  assign m_axi_Matrix_data_2_ARCACHE = 4'h3;
  assign m_axi_Matrix_data_2_ARID = 1'h0;
  assign m_axi_Matrix_data_2_ARLEN = 8'h0;
  assign m_axi_Matrix_data_2_ARLOCK = 1'h0;
  assign m_axi_Matrix_data_2_ARPROT = 3'h0;
  assign m_axi_Matrix_data_2_ARQOS = 4'h0;
  assign m_axi_Matrix_data_2_ARSIZE = 3'h6;
  assign m_axi_Matrix_data_2_ARVALID = ~_GEN_5 & _GEN_4 & _selectedMatrixRResp_T_2;
  assign m_axi_Matrix_data_2_RREADY = ~_GEN_8 & _GEN_6 & _selectedMatrixRResp_T_2;
  assign m_axi_Matrix_data_2_WDATA = 512'h0;
  assign m_axi_Matrix_data_2_WLAST = 1'h1;
  assign m_axi_Matrix_data_2_WSTRB = 64'hFFFFFFFFFFFFFFFF;
  assign m_axi_Matrix_data_2_WVALID = 1'h0;
  assign m_axi_Matrix_data_3_AWADDR = 64'h0;
  assign m_axi_Matrix_data_3_AWBURST = 2'h1;
  assign m_axi_Matrix_data_3_AWCACHE = 4'h3;
  assign m_axi_Matrix_data_3_AWID = 1'h0;
  assign m_axi_Matrix_data_3_AWLEN = 8'h0;
  assign m_axi_Matrix_data_3_AWLOCK = 1'h0;
  assign m_axi_Matrix_data_3_AWPROT = 3'h0;
  assign m_axi_Matrix_data_3_AWQOS = 4'h0;
  assign m_axi_Matrix_data_3_AWSIZE = 3'h6;
  assign m_axi_Matrix_data_3_AWVALID = 1'h0;
  assign m_axi_Matrix_data_3_BREADY = 1'h0;
  assign m_axi_Matrix_data_3_ARADDR =
    _GEN_5 | ~(_GEN_4 & _selectedMatrixRResp_T_3) ? 64'h0 : argPtr_4;
  assign m_axi_Matrix_data_3_ARBURST = 2'h1;
  assign m_axi_Matrix_data_3_ARCACHE = 4'h3;
  assign m_axi_Matrix_data_3_ARID = 1'h0;
  assign m_axi_Matrix_data_3_ARLEN = 8'h0;
  assign m_axi_Matrix_data_3_ARLOCK = 1'h0;
  assign m_axi_Matrix_data_3_ARPROT = 3'h0;
  assign m_axi_Matrix_data_3_ARQOS = 4'h0;
  assign m_axi_Matrix_data_3_ARSIZE = 3'h6;
  assign m_axi_Matrix_data_3_ARVALID = ~_GEN_5 & _GEN_4 & _selectedMatrixRResp_T_3;
  assign m_axi_Matrix_data_3_RREADY = ~_GEN_8 & _GEN_6 & _selectedMatrixRResp_T_3;
  assign m_axi_Matrix_data_3_WDATA = 512'h0;
  assign m_axi_Matrix_data_3_WLAST = 1'h1;
  assign m_axi_Matrix_data_3_WSTRB = 64'hFFFFFFFFFFFFFFFF;
  assign m_axi_Matrix_data_3_WVALID = 1'h0;
  assign m_axi_Matrix_data_4_AWADDR = 64'h0;
  assign m_axi_Matrix_data_4_AWBURST = 2'h1;
  assign m_axi_Matrix_data_4_AWCACHE = 4'h3;
  assign m_axi_Matrix_data_4_AWID = 1'h0;
  assign m_axi_Matrix_data_4_AWLEN = 8'h0;
  assign m_axi_Matrix_data_4_AWLOCK = 1'h0;
  assign m_axi_Matrix_data_4_AWPROT = 3'h0;
  assign m_axi_Matrix_data_4_AWQOS = 4'h0;
  assign m_axi_Matrix_data_4_AWSIZE = 3'h6;
  assign m_axi_Matrix_data_4_AWVALID = 1'h0;
  assign m_axi_Matrix_data_4_BREADY = 1'h0;
  assign m_axi_Matrix_data_4_ARADDR =
    _GEN_5 | ~(_GEN_4 & _selectedMatrixRResp_T_4) ? 64'h0 : argPtr_5;
  assign m_axi_Matrix_data_4_ARBURST = 2'h1;
  assign m_axi_Matrix_data_4_ARCACHE = 4'h3;
  assign m_axi_Matrix_data_4_ARID = 1'h0;
  assign m_axi_Matrix_data_4_ARLEN = 8'h0;
  assign m_axi_Matrix_data_4_ARLOCK = 1'h0;
  assign m_axi_Matrix_data_4_ARPROT = 3'h0;
  assign m_axi_Matrix_data_4_ARQOS = 4'h0;
  assign m_axi_Matrix_data_4_ARSIZE = 3'h6;
  assign m_axi_Matrix_data_4_ARVALID = ~_GEN_5 & _GEN_4 & _selectedMatrixRResp_T_4;
  assign m_axi_Matrix_data_4_RREADY = ~_GEN_8 & _GEN_6 & _selectedMatrixRResp_T_4;
  assign m_axi_Matrix_data_4_WDATA = 512'h0;
  assign m_axi_Matrix_data_4_WLAST = 1'h1;
  assign m_axi_Matrix_data_4_WSTRB = 64'hFFFFFFFFFFFFFFFF;
  assign m_axi_Matrix_data_4_WVALID = 1'h0;
  assign m_axi_Matrix_data_5_AWADDR = 64'h0;
  assign m_axi_Matrix_data_5_AWBURST = 2'h1;
  assign m_axi_Matrix_data_5_AWCACHE = 4'h3;
  assign m_axi_Matrix_data_5_AWID = 1'h0;
  assign m_axi_Matrix_data_5_AWLEN = 8'h0;
  assign m_axi_Matrix_data_5_AWLOCK = 1'h0;
  assign m_axi_Matrix_data_5_AWPROT = 3'h0;
  assign m_axi_Matrix_data_5_AWQOS = 4'h0;
  assign m_axi_Matrix_data_5_AWSIZE = 3'h6;
  assign m_axi_Matrix_data_5_AWVALID = 1'h0;
  assign m_axi_Matrix_data_5_BREADY = 1'h0;
  assign m_axi_Matrix_data_5_ARADDR =
    _GEN_5 | ~(_GEN_4 & _selectedMatrixRResp_T_5) ? 64'h0 : argPtr_6;
  assign m_axi_Matrix_data_5_ARBURST = 2'h1;
  assign m_axi_Matrix_data_5_ARCACHE = 4'h3;
  assign m_axi_Matrix_data_5_ARID = 1'h0;
  assign m_axi_Matrix_data_5_ARLEN = 8'h0;
  assign m_axi_Matrix_data_5_ARLOCK = 1'h0;
  assign m_axi_Matrix_data_5_ARPROT = 3'h0;
  assign m_axi_Matrix_data_5_ARQOS = 4'h0;
  assign m_axi_Matrix_data_5_ARSIZE = 3'h6;
  assign m_axi_Matrix_data_5_ARVALID = ~_GEN_5 & _GEN_4 & _selectedMatrixRResp_T_5;
  assign m_axi_Matrix_data_5_RREADY = ~_GEN_8 & _GEN_6 & _selectedMatrixRResp_T_5;
  assign m_axi_Matrix_data_5_WDATA = 512'h0;
  assign m_axi_Matrix_data_5_WLAST = 1'h1;
  assign m_axi_Matrix_data_5_WSTRB = 64'hFFFFFFFFFFFFFFFF;
  assign m_axi_Matrix_data_5_WVALID = 1'h0;
  assign m_axi_Matrix_data_6_AWADDR = 64'h0;
  assign m_axi_Matrix_data_6_AWBURST = 2'h1;
  assign m_axi_Matrix_data_6_AWCACHE = 4'h3;
  assign m_axi_Matrix_data_6_AWID = 1'h0;
  assign m_axi_Matrix_data_6_AWLEN = 8'h0;
  assign m_axi_Matrix_data_6_AWLOCK = 1'h0;
  assign m_axi_Matrix_data_6_AWPROT = 3'h0;
  assign m_axi_Matrix_data_6_AWQOS = 4'h0;
  assign m_axi_Matrix_data_6_AWSIZE = 3'h6;
  assign m_axi_Matrix_data_6_AWVALID = 1'h0;
  assign m_axi_Matrix_data_6_BREADY = 1'h0;
  assign m_axi_Matrix_data_6_ARADDR =
    _GEN_5 | ~(_GEN_4 & _selectedMatrixRResp_T_6) ? 64'h0 : argPtr_7;
  assign m_axi_Matrix_data_6_ARBURST = 2'h1;
  assign m_axi_Matrix_data_6_ARCACHE = 4'h3;
  assign m_axi_Matrix_data_6_ARID = 1'h0;
  assign m_axi_Matrix_data_6_ARLEN = 8'h0;
  assign m_axi_Matrix_data_6_ARLOCK = 1'h0;
  assign m_axi_Matrix_data_6_ARPROT = 3'h0;
  assign m_axi_Matrix_data_6_ARQOS = 4'h0;
  assign m_axi_Matrix_data_6_ARSIZE = 3'h6;
  assign m_axi_Matrix_data_6_ARVALID = ~_GEN_5 & _GEN_4 & _selectedMatrixRResp_T_6;
  assign m_axi_Matrix_data_6_RREADY = ~_GEN_8 & _GEN_6 & _selectedMatrixRResp_T_6;
  assign m_axi_Matrix_data_6_WDATA = 512'h0;
  assign m_axi_Matrix_data_6_WLAST = 1'h1;
  assign m_axi_Matrix_data_6_WSTRB = 64'hFFFFFFFFFFFFFFFF;
  assign m_axi_Matrix_data_6_WVALID = 1'h0;
  assign m_axi_Matrix_data_7_AWADDR = 64'h0;
  assign m_axi_Matrix_data_7_AWBURST = 2'h1;
  assign m_axi_Matrix_data_7_AWCACHE = 4'h3;
  assign m_axi_Matrix_data_7_AWID = 1'h0;
  assign m_axi_Matrix_data_7_AWLEN = 8'h0;
  assign m_axi_Matrix_data_7_AWLOCK = 1'h0;
  assign m_axi_Matrix_data_7_AWPROT = 3'h0;
  assign m_axi_Matrix_data_7_AWQOS = 4'h0;
  assign m_axi_Matrix_data_7_AWSIZE = 3'h6;
  assign m_axi_Matrix_data_7_AWVALID = 1'h0;
  assign m_axi_Matrix_data_7_BREADY = 1'h0;
  assign m_axi_Matrix_data_7_ARADDR =
    _GEN_5 | ~(_GEN_4 & (&matrixIndex)) ? 64'h0 : argPtr_8;
  assign m_axi_Matrix_data_7_ARBURST = 2'h1;
  assign m_axi_Matrix_data_7_ARCACHE = 4'h3;
  assign m_axi_Matrix_data_7_ARID = 1'h0;
  assign m_axi_Matrix_data_7_ARLEN = 8'h0;
  assign m_axi_Matrix_data_7_ARLOCK = 1'h0;
  assign m_axi_Matrix_data_7_ARPROT = 3'h0;
  assign m_axi_Matrix_data_7_ARQOS = 4'h0;
  assign m_axi_Matrix_data_7_ARSIZE = 3'h6;
  assign m_axi_Matrix_data_7_ARVALID = ~_GEN_5 & _GEN_4 & (&matrixIndex);
  assign m_axi_Matrix_data_7_RREADY = ~_GEN_8 & _GEN_6 & (&matrixIndex);
  assign m_axi_Matrix_data_7_WDATA = 512'h0;
  assign m_axi_Matrix_data_7_WLAST = 1'h1;
  assign m_axi_Matrix_data_7_WSTRB = 64'hFFFFFFFFFFFFFFFF;
  assign m_axi_Matrix_data_7_WVALID = 1'h0;
  assign m_axi_X_AWADDR = 64'h0;
  assign m_axi_X_AWBURST = 2'h1;
  assign m_axi_X_AWCACHE = 4'h3;
  assign m_axi_X_AWID = 1'h0;
  assign m_axi_X_AWLEN = 8'h0;
  assign m_axi_X_AWLOCK = 1'h0;
  assign m_axi_X_AWPROT = 3'h0;
  assign m_axi_X_AWQOS = 4'h0;
  assign m_axi_X_AWSIZE = 3'h6;
  assign m_axi_X_AWVALID = 1'h0;
  assign m_axi_X_BREADY = 1'h0;
  assign m_axi_X_ARADDR = _GEN_10 | ~_GEN_9 ? 64'h0 : argPtr_9;
  assign m_axi_X_ARBURST = 2'h1;
  assign m_axi_X_ARCACHE = 4'h3;
  assign m_axi_X_ARID = 1'h0;
  assign m_axi_X_ARLEN = 8'h0;
  assign m_axi_X_ARLOCK = 1'h0;
  assign m_axi_X_ARPROT = 3'h0;
  assign m_axi_X_ARQOS = 4'h0;
  assign m_axi_X_ARSIZE = 3'h6;
  assign m_axi_X_ARVALID = ~_GEN_10 & _GEN_9;
  assign m_axi_X_RREADY = ~_GEN_12 & _GEN_11;
  assign m_axi_X_WDATA = 512'h0;
  assign m_axi_X_WLAST = 1'h1;
  assign m_axi_X_WSTRB = 64'hFFFFFFFFFFFFFFFF;
  assign m_axi_X_WVALID = 1'h0;
  assign m_axi_Y_out_AWADDR = _GEN_14 | ~_GEN_13 ? 64'h0 : argPtr_10;
  assign m_axi_Y_out_AWBURST = 2'h1;
  assign m_axi_Y_out_AWCACHE = 4'h3;
  assign m_axi_Y_out_AWID = 1'h0;
  assign m_axi_Y_out_AWLEN = 8'h0;
  assign m_axi_Y_out_AWLOCK = 1'h0;
  assign m_axi_Y_out_AWPROT = 3'h0;
  assign m_axi_Y_out_AWQOS = 4'h0;
  assign m_axi_Y_out_AWSIZE = 3'h2;
  assign m_axi_Y_out_AWVALID = ~_GEN_14 & _GEN_13;
  assign m_axi_Y_out_BREADY = ~_GEN_17 & _GEN_16;
  assign m_axi_Y_out_ARADDR = 64'h0;
  assign m_axi_Y_out_ARBURST = 2'h1;
  assign m_axi_Y_out_ARCACHE = 4'h3;
  assign m_axi_Y_out_ARID = 1'h0;
  assign m_axi_Y_out_ARLEN = 8'h0;
  assign m_axi_Y_out_ARLOCK = 1'h0;
  assign m_axi_Y_out_ARPROT = 3'h0;
  assign m_axi_Y_out_ARQOS = 4'h0;
  assign m_axi_Y_out_ARSIZE = 3'h2;
  assign m_axi_Y_out_ARVALID = 1'h0;
  assign m_axi_Y_out_RREADY = 1'h0;
  assign m_axi_Y_out_WDATA = 32'h0;
  assign m_axi_Y_out_WLAST = 1'h1;
  assign m_axi_Y_out_WSTRB = 4'hF;
  assign m_axi_Y_out_WVALID =
    ~(~(|state) | _GEN_1 | _GEN_2 | _GEN_4 | _GEN_6 | _GEN_9 | _GEN_11 | _GEN_13)
    & _GEN_15;
  assign m_axi_Status_AWADDR =
    _GEN_19 | ~_GEN_18 ? 64'h0 : argPtr_11 + {57'h0, statusIndex, 2'h0};
  assign m_axi_Status_AWBURST = 2'h1;
  assign m_axi_Status_AWCACHE = 4'h3;
  assign m_axi_Status_AWID = 1'h0;
  assign m_axi_Status_AWLEN = 8'h0;
  assign m_axi_Status_AWLOCK = 1'h0;
  assign m_axi_Status_AWPROT = 3'h0;
  assign m_axi_Status_AWQOS = 4'h0;
  assign m_axi_Status_AWSIZE = 3'h2;
  assign m_axi_Status_AWVALID = ~_GEN_19 & _GEN_18;
  assign m_axi_Status_BREADY = ~(~(|state) | _GEN_24) & _GEN_22;
  assign m_axi_Status_ARADDR = 64'h0;
  assign m_axi_Status_ARBURST = 2'h1;
  assign m_axi_Status_ARCACHE = 4'h3;
  assign m_axi_Status_ARID = 1'h0;
  assign m_axi_Status_ARLEN = 8'h0;
  assign m_axi_Status_ARLOCK = 1'h0;
  assign m_axi_Status_ARPROT = 3'h0;
  assign m_axi_Status_ARQOS = 4'h0;
  assign m_axi_Status_ARSIZE = 3'h2;
  assign m_axi_Status_ARVALID = 1'h0;
  assign m_axi_Status_RREADY = 1'h0;
  assign m_axi_Status_WDATA =
    _GEN_21 | ~_GEN_20
      ? 32'h0
      : statusIndex == 5'h0
          ? 32'h1
          : statusIndex == 5'h1
              ? 32'h43535056
              : statusIndex == 5'h2
                  ? rowNum
                  : statusIndex == 5'h3
                      ? columnNum
                      : statusIndex == 5'h4
                          ? batchNum
                          : statusIndex == 5'h5
                              ? matrixLen
                              : statusIndex == 5'h6
                                  ? iterationNum
                                  : statusIndex == 5'h7
                                      ? ptr0
                                      : statusIndex == 5'h8
                                          ? x0[31:0]
                                          : statusIndex == 5'h9
                                              ? matrixFirst_0[31:0]
                                              : statusIndex == 5'hA
                                                  ? matrixFirst_1[31:0]
                                                  : statusIndex == 5'hB
                                                      ? matrixFirst_2[31:0]
                                                      : statusIndex == 5'hC
                                                          ? matrixFirst_3[31:0]
                                                          : statusIndex == 5'hD
                                                              ? {28'h0, state}
                                                              : statusIndex == 5'hE
                                                                  ? {30'h0, lastRresp}
                                                                  : _GEN
                                                                      ? {30'h0, lastBresp}
                                                                      : 32'h0;
  assign m_axi_Status_WLAST = 1'h1;
  assign m_axi_Status_WSTRB = 4'hF;
  assign m_axi_Status_WVALID = ~_GEN_21 & _GEN_20;
  assign m_axi_Metrics_AWADDR =
    _GEN_26 | ~_GEN_25 ? 64'h0 : argPtr_12 + {56'h0, metricIndex, 3'h0};
  assign m_axi_Metrics_AWBURST = 2'h1;
  assign m_axi_Metrics_AWCACHE = 4'h3;
  assign m_axi_Metrics_AWID = 1'h0;
  assign m_axi_Metrics_AWLEN = 8'h0;
  assign m_axi_Metrics_AWLOCK = 1'h0;
  assign m_axi_Metrics_AWPROT = 3'h0;
  assign m_axi_Metrics_AWQOS = 4'h0;
  assign m_axi_Metrics_AWSIZE = 3'h3;
  assign m_axi_Metrics_AWVALID = ~_GEN_26 & _GEN_25;
  assign m_axi_Metrics_BREADY = &state;
  assign m_axi_Metrics_ARADDR = 64'h0;
  assign m_axi_Metrics_ARBURST = 2'h1;
  assign m_axi_Metrics_ARCACHE = 4'h3;
  assign m_axi_Metrics_ARID = 1'h0;
  assign m_axi_Metrics_ARLEN = 8'h0;
  assign m_axi_Metrics_ARLOCK = 1'h0;
  assign m_axi_Metrics_ARPROT = 3'h0;
  assign m_axi_Metrics_ARQOS = 4'h0;
  assign m_axi_Metrics_ARSIZE = 3'h3;
  assign m_axi_Metrics_ARVALID = 1'h0;
  assign m_axi_Metrics_RREADY = 1'h0;
  assign m_axi_Metrics_WDATA =
    _GEN_28 | ~_GEN_27
      ? 64'h0
      : metricIndex == 5'h0
          ? 64'h4353504D56384348
          : metricIndex == 5'h1
              ? cycleCounter
              : metricIndex == 5'h2
                  ? {batchNum, rowNum}
                  : metricIndex == 5'h3
                      ? {matrixLen, columnNum}
                      : metricIndex == 5'h4
                          ? argPtr_0
                          : metricIndex == 5'h5
                              ? argPtr_9
                              : metricIndex == 5'h6
                                  ? argPtr_10
                                  : metricIndex == 5'h7
                                      ? x0[63:0]
                                      : metricIndex == 5'h8
                                          ? matrixFirst_0[63:0]
                                          : metricIndex == 5'h9
                                              ? matrixFirst_1[63:0]
                                              : metricIndex == 5'hA
                                                  ? matrixFirst_2[63:0]
                                                  : metricIndex == 5'hB
                                                      ? matrixFirst_3[63:0]
                                                      : metricIndex == 5'hC
                                                          ? matrixFirst_4[63:0]
                                                          : metricIndex == 5'hD
                                                              ? matrixFirst_5[63:0]
                                                              : metricIndex == 5'hE
                                                                  ? matrixFirst_6[63:0]
                                                                  : _GEN_0
                                                                      ? matrixFirst_7[63:0]
                                                                      : 64'h0;
  assign m_axi_Metrics_WLAST = 1'h1;
  assign m_axi_Metrics_WSTRB = 8'hFF;
  assign m_axi_Metrics_WVALID = ~_GEN_28 & _GEN_27;
endmodule
