`timescale 1 ns / 1 ps

// Regression model for the generated TAPA scatter pipeline.
//
// The real module is generated by Vitis HLS and has the same long module name
// below.  The current simulator hits an internal fault when that generated
// pipeline is compiled together with the custom owner-bank RTL testbench, so
// this model preserves the external FIFO/m_axi-lite stream protocol and the
// exact tagged word unpacking used by the generated RTL:
//   packet_idx = word[31:0]
//   pair_lane  = word[63:32]
//   value0     = word[95:64]
//   value1     = word[127:96]
//
// It is intentionally small: the purpose is to catch owner-bank output packing,
// stream drain, and write-response completion bugs before spending a bitstream
// build on them.
module CuperSpmvOnly_TaggedScatterWriterOoo_PipelineScatterModel (
    input ap_clk,
    input ap_rst,
    input ap_start,
    output reg ap_done,
    output ap_idle,
    output ap_ready,
    input [31:0] scalar_writes_total,
    input [8:0] Y_out_write_resp_s_dout,
    input Y_out_write_resp_s_empty_n,
    output reg Y_out_write_resp_s_read,
    input [31:0] tagged_pairs_total,
    input [128:0] Vector_Y_Tagged_Stream_0_dout,
    input Vector_Y_Tagged_Stream_0_empty_n,
    output reg Vector_Y_Tagged_Stream_0_read,
    input [128:0] Vector_Y_Tagged_Stream_1_dout,
    input Vector_Y_Tagged_Stream_1_empty_n,
    output reg Vector_Y_Tagged_Stream_1_read,
    input [128:0] Vector_Y_Tagged_Stream_2_dout,
    input Vector_Y_Tagged_Stream_2_empty_n,
    output reg Vector_Y_Tagged_Stream_2_read,
    input [128:0] Vector_Y_Tagged_Stream_3_dout,
    input Vector_Y_Tagged_Stream_3_empty_n,
    output reg Vector_Y_Tagged_Stream_3_read,
    input [128:0] Vector_Y_Tagged_Stream_4_dout,
    input Vector_Y_Tagged_Stream_4_empty_n,
    output reg Vector_Y_Tagged_Stream_4_read,
    input [128:0] Vector_Y_Tagged_Stream_5_dout,
    input Vector_Y_Tagged_Stream_5_empty_n,
    output reg Vector_Y_Tagged_Stream_5_read,
    input [128:0] Vector_Y_Tagged_Stream_6_dout,
    input Vector_Y_Tagged_Stream_6_empty_n,
    output reg Vector_Y_Tagged_Stream_6_read,
    input [128:0] Vector_Y_Tagged_Stream_7_dout,
    input Vector_Y_Tagged_Stream_7_empty_n,
    output reg Vector_Y_Tagged_Stream_7_read,
    input [128:0] Vector_Y_Tagged_Stream_8_dout,
    input Vector_Y_Tagged_Stream_8_empty_n,
    output reg Vector_Y_Tagged_Stream_8_read,
    input [128:0] Vector_Y_Tagged_Stream_9_dout,
    input Vector_Y_Tagged_Stream_9_empty_n,
    output reg Vector_Y_Tagged_Stream_9_read,
    input [128:0] Vector_Y_Tagged_Stream_10_dout,
    input Vector_Y_Tagged_Stream_10_empty_n,
    output reg Vector_Y_Tagged_Stream_10_read,
    input [128:0] Vector_Y_Tagged_Stream_11_dout,
    input Vector_Y_Tagged_Stream_11_empty_n,
    output reg Vector_Y_Tagged_Stream_11_read,
    input [128:0] Vector_Y_Tagged_Stream_12_dout,
    input Vector_Y_Tagged_Stream_12_empty_n,
    output reg Vector_Y_Tagged_Stream_12_read,
    input [128:0] Vector_Y_Tagged_Stream_13_dout,
    input Vector_Y_Tagged_Stream_13_empty_n,
    output reg Vector_Y_Tagged_Stream_13_read,
    input [128:0] Vector_Y_Tagged_Stream_14_dout,
    input Vector_Y_Tagged_Stream_14_empty_n,
    output reg Vector_Y_Tagged_Stream_14_read,
    input [128:0] Vector_Y_Tagged_Stream_15_dout,
    input Vector_Y_Tagged_Stream_15_empty_n,
    output reg Vector_Y_Tagged_Stream_15_read,
    output reg [63:0] Y_out_write_addr_s_din,
    input Y_out_write_addr_s_full_n,
    output reg Y_out_write_addr_s_write,
    output reg [32:0] Y_out_write_data_s_din,
    input Y_out_write_data_s_full_n,
    output reg Y_out_write_data_s_write,
    input [63:0] Y_out_write_addr_offset_load
);
    reg active;
    reg pending_valid;
    reg [31:0] pending_addr;
    reg [31:0] pending_data;
    reg next_valid;
    reg [31:0] next_addr;
    reg [31:0] next_data;
    reg [31:0] pair_count;
    reg [31:0] response_count;
    reg [3:0] channel_cursor;

    reg selected_empty_n;
    reg [128:0] selected_word;
    reg [31:0] response_count_next;
    reg [31:0] base_addr;

    assign ap_idle = !active;
    assign ap_ready = ap_done;

    always @(*) begin
        selected_empty_n = 1'b0;
        selected_word = 129'd0;
        case (channel_cursor)
            4'd0: begin selected_empty_n = Vector_Y_Tagged_Stream_0_empty_n; selected_word = Vector_Y_Tagged_Stream_0_dout; end
            4'd1: begin selected_empty_n = Vector_Y_Tagged_Stream_1_empty_n; selected_word = Vector_Y_Tagged_Stream_1_dout; end
            4'd2: begin selected_empty_n = Vector_Y_Tagged_Stream_2_empty_n; selected_word = Vector_Y_Tagged_Stream_2_dout; end
            4'd3: begin selected_empty_n = Vector_Y_Tagged_Stream_3_empty_n; selected_word = Vector_Y_Tagged_Stream_3_dout; end
            4'd4: begin selected_empty_n = Vector_Y_Tagged_Stream_4_empty_n; selected_word = Vector_Y_Tagged_Stream_4_dout; end
            4'd5: begin selected_empty_n = Vector_Y_Tagged_Stream_5_empty_n; selected_word = Vector_Y_Tagged_Stream_5_dout; end
            4'd6: begin selected_empty_n = Vector_Y_Tagged_Stream_6_empty_n; selected_word = Vector_Y_Tagged_Stream_6_dout; end
            4'd7: begin selected_empty_n = Vector_Y_Tagged_Stream_7_empty_n; selected_word = Vector_Y_Tagged_Stream_7_dout; end
            4'd8: begin selected_empty_n = Vector_Y_Tagged_Stream_8_empty_n; selected_word = Vector_Y_Tagged_Stream_8_dout; end
            4'd9: begin selected_empty_n = Vector_Y_Tagged_Stream_9_empty_n; selected_word = Vector_Y_Tagged_Stream_9_dout; end
            4'd10: begin selected_empty_n = Vector_Y_Tagged_Stream_10_empty_n; selected_word = Vector_Y_Tagged_Stream_10_dout; end
            4'd11: begin selected_empty_n = Vector_Y_Tagged_Stream_11_empty_n; selected_word = Vector_Y_Tagged_Stream_11_dout; end
            4'd12: begin selected_empty_n = Vector_Y_Tagged_Stream_12_empty_n; selected_word = Vector_Y_Tagged_Stream_12_dout; end
            4'd13: begin selected_empty_n = Vector_Y_Tagged_Stream_13_empty_n; selected_word = Vector_Y_Tagged_Stream_13_dout; end
            4'd14: begin selected_empty_n = Vector_Y_Tagged_Stream_14_empty_n; selected_word = Vector_Y_Tagged_Stream_14_dout; end
            default: begin selected_empty_n = Vector_Y_Tagged_Stream_15_empty_n; selected_word = Vector_Y_Tagged_Stream_15_dout; end
        endcase
    end

    always @(posedge ap_clk) begin
        if (ap_rst) begin
            active <= 1'b0;
            ap_done <= 1'b0;
            pending_valid <= 1'b0;
            pending_addr <= 32'd0;
            pending_data <= 32'd0;
            next_valid <= 1'b0;
            next_addr <= 32'd0;
            next_data <= 32'd0;
            pair_count <= 32'd0;
            response_count <= 32'd0;
            channel_cursor <= 4'd0;
        end else begin
            ap_done <= 1'b0;
            Vector_Y_Tagged_Stream_0_read <= 1'b0;
            Vector_Y_Tagged_Stream_1_read <= 1'b0;
            Vector_Y_Tagged_Stream_2_read <= 1'b0;
            Vector_Y_Tagged_Stream_3_read <= 1'b0;
            Vector_Y_Tagged_Stream_4_read <= 1'b0;
            Vector_Y_Tagged_Stream_5_read <= 1'b0;
            Vector_Y_Tagged_Stream_6_read <= 1'b0;
            Vector_Y_Tagged_Stream_7_read <= 1'b0;
            Vector_Y_Tagged_Stream_8_read <= 1'b0;
            Vector_Y_Tagged_Stream_9_read <= 1'b0;
            Vector_Y_Tagged_Stream_10_read <= 1'b0;
            Vector_Y_Tagged_Stream_11_read <= 1'b0;
            Vector_Y_Tagged_Stream_12_read <= 1'b0;
            Vector_Y_Tagged_Stream_13_read <= 1'b0;
            Vector_Y_Tagged_Stream_14_read <= 1'b0;
            Vector_Y_Tagged_Stream_15_read <= 1'b0;
            Y_out_write_resp_s_read <= 1'b0;
            Y_out_write_addr_s_write <= 1'b0;
            Y_out_write_data_s_write <= 1'b0;

            if (!active) begin
                if (ap_start) begin
                    active <= 1'b1;
                    pending_valid <= 1'b0;
                    next_valid <= 1'b0;
                    pair_count <= 32'd0;
                    response_count <= 32'd0;
                    channel_cursor <= 4'd0;
                end
            end else begin
                response_count_next = response_count;

                if (!pending_valid && next_valid) begin
                    pending_addr <= next_addr;
                    pending_data <= next_data;
                    pending_valid <= 1'b1;
                    next_valid <= 1'b0;
                end

                if (!pending_valid && !next_valid &&
                    pair_count < tagged_pairs_total && selected_empty_n) begin
                    base_addr = (selected_word[31:0] << 4) +
                                (selected_word[63:32] << 1);
                    pending_addr <= base_addr;
                    pending_data <= selected_word[95:64];
                    pending_valid <= 1'b1;
                    next_addr <= base_addr + 32'd1;
                    next_data <= selected_word[127:96];
                    next_valid <= 1'b1;
                    pair_count <= pair_count + 32'd1;
                    case (channel_cursor)
                        4'd0: Vector_Y_Tagged_Stream_0_read <= 1'b1;
                        4'd1: Vector_Y_Tagged_Stream_1_read <= 1'b1;
                        4'd2: Vector_Y_Tagged_Stream_2_read <= 1'b1;
                        4'd3: Vector_Y_Tagged_Stream_3_read <= 1'b1;
                        4'd4: Vector_Y_Tagged_Stream_4_read <= 1'b1;
                        4'd5: Vector_Y_Tagged_Stream_5_read <= 1'b1;
                        4'd6: Vector_Y_Tagged_Stream_6_read <= 1'b1;
                        4'd7: Vector_Y_Tagged_Stream_7_read <= 1'b1;
                        4'd8: Vector_Y_Tagged_Stream_8_read <= 1'b1;
                        4'd9: Vector_Y_Tagged_Stream_9_read <= 1'b1;
                        4'd10: Vector_Y_Tagged_Stream_10_read <= 1'b1;
                        4'd11: Vector_Y_Tagged_Stream_11_read <= 1'b1;
                        4'd12: Vector_Y_Tagged_Stream_12_read <= 1'b1;
                        4'd13: Vector_Y_Tagged_Stream_13_read <= 1'b1;
                        4'd14: Vector_Y_Tagged_Stream_14_read <= 1'b1;
                        default: Vector_Y_Tagged_Stream_15_read <= 1'b1;
                    endcase
                end

                if (pending_valid &&
                    Y_out_write_addr_s_full_n &&
                    Y_out_write_data_s_full_n) begin
                    Y_out_write_addr_s_din <= Y_out_write_addr_offset_load +
                                              {pending_addr, 2'b00};
                    Y_out_write_data_s_din <= {1'b0, pending_data};
                    Y_out_write_addr_s_write <= 1'b1;
                    Y_out_write_data_s_write <= 1'b1;
                    pending_valid <= 1'b0;
                end

                if (Y_out_write_resp_s_empty_n) begin
                    Y_out_write_resp_s_read <= 1'b1;
                    response_count_next = response_count_next +
                                          {23'd0, Y_out_write_resp_s_dout[7:0]} +
                                          32'd1;
                end
                response_count <= response_count_next;

                channel_cursor <= channel_cursor + 4'd1;

                if (response_count_next >= scalar_writes_total) begin
                    active <= 1'b0;
                    ap_done <= 1'b1;
                end
            end
        end
    end
endmodule
